<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZUzyRwa_SyliusMollie_Twig_Component_EmailTemplate_FormaddCollectionItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zUzyRwa.sylius_mollie.twig.component.email_template.form::addCollectionItem()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zUzyRwa.sylius_mollie.twig.component.email_template.form::addCollectionItem()'] = ($container->privates['.service_locator.zUzyRwa'] ?? $container->load('get_ServiceLocator_ZUzyRwaService'))->withContext('sylius_mollie.twig.component.email_template.form::addCollectionItem()', $container);
    }
}
