<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sylius_Console_Command_PriceHistory_Clear_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sylius.console.command.price_history.clear.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sylius.console.command.price_history.clear.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sylius:price-history:clear', [], 'Clears the price history up to a given number of days ago', false, #[\Closure(name: 'sylius.console.command.price_history.clear', class: 'Sylius\\Bundle\\CoreBundle\\PriceHistory\\Console\\Command\\ClearPriceHistoryCommand')] fn (): \Sylius\Bundle\CoreBundle\PriceHistory\Console\Command\ClearPriceHistoryCommand => ($container->services['sylius.console.command.price_history.clear'] ?? $container->load('getSylius_Console_Command_PriceHistory_ClearService')));
    }
}
