<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sylius_Console_Command_CancelUnpaidOrders_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sylius.console.command.cancel_unpaid_orders.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sylius.console.command.cancel_unpaid_orders.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sylius:cancel-unpaid-orders', [], 'Removes order that have been unpaid for a configured period. Configuration parameter - sylius_order.order_expiration_period.', false, #[\Closure(name: 'sylius.console.command.cancel_unpaid_orders', class: 'Sylius\\Bundle\\CoreBundle\\Console\\Command\\CancelUnpaidOrdersCommand')] fn (): \Sylius\Bundle\CoreBundle\Console\Command\CancelUnpaidOrdersCommand => ($container->services['sylius.console.command.cancel_unpaid_orders'] ?? $container->load('getSylius_Console_Command_CancelUnpaidOrdersService')));
    }
}
