<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_4f3Pv0tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.4f3Pv0t' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/AddItemToCartHandler.php';

        return $container->privates['.messenger.handler_descriptor.4f3Pv0t'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Sylius\Bundle\ApiBundle\CommandHandler\Cart\AddItemToCartHandler(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['sylius.repository.product_variant'] ?? $container->load('getSylius_Repository_ProductVariantService')), ($container->privates['sylius.modifier.order'] ?? $container->load('getSylius_Modifier_OrderService')), ($container->services['sylius.factory.order_item'] ?? $container->load('getSylius_Factory_OrderItemService')), ($container->privates['sylius.modifier.cart.limiting_order_item_quantity'] ?? $container->load('getSylius_Modifier_Cart_LimitingOrderItemQuantityService'))), ['bus' => 'sylius.command_bus']);
    }
}
