<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sylius_Console_Command_GenerateEncryptionKey_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sylius.console.command.generate_encryption_key.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sylius.console.command.generate_encryption_key.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sylius:payment:generate-key', [], 'Generate a key for Sylius payment encryption.', false, #[\Closure(name: 'sylius.console.command.generate_encryption_key', class: 'Sylius\\Bundle\\PaymentBundle\\Console\\Command\\GenerateEncryptionKeyCommand')] fn (): \Sylius\Bundle\PaymentBundle\Console\Command\GenerateEncryptionKeyCommand => ($container->services['sylius.console.command.generate_encryption_key'] ?? $container->load('getSylius_Console_Command_GenerateEncryptionKeyService')));
    }
}
