<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_2VZliT2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.2VZliT2' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/DisableCatalogPromotionHandler.php';

        $a = ($container->privates['sylius.processor.catalog_promotion.all_product_variant'] ?? $container->load('getSylius_Processor_CatalogPromotion_AllProductVariantService'));

        if (isset($container->privates['.messenger.handler_descriptor.2VZliT2'])) {
            return $container->privates['.messenger.handler_descriptor.2VZliT2'];
        }

        return $container->privates['.messenger.handler_descriptor.2VZliT2'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Sylius\Bundle\CoreBundle\CatalogPromotion\CommandHandler\DisableCatalogPromotionHandler(($container->services['sylius.repository.catalog_promotion'] ?? $container->load('getSylius_Repository_CatalogPromotionService')), $a), ['bus' => 'sylius.command_bus']);
    }
}
