<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sylius_Console_Command_Install_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sylius.console.command.install.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sylius.console.command.install.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sylius:install', [], 'Installs Sylius in your preferred environment.', false, #[\Closure(name: 'sylius.console.command.install', class: 'Sylius\\Bundle\\CoreBundle\\Console\\Command\\InstallCommand')] fn (): \Sylius\Bundle\CoreBundle\Console\Command\InstallCommand => ($container->services['sylius.console.command.install'] ?? $container->load('getSylius_Console_Command_InstallService')));
    }
}
