<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_E8ECzyKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.e8ECzyK' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CommandHandler/Admin/Account/RequestResetPasswordEmailHandler.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['.messenger.handler_descriptor.e8ECzyK'])) {
            return $container->privates['.messenger.handler_descriptor.e8ECzyK'];
        }

        return $container->privates['.messenger.handler_descriptor.e8ECzyK'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Sylius\Bundle\CoreBundle\CommandHandler\Admin\Account\RequestResetPasswordEmailHandler(($container->services['sylius.repository.admin_user'] ?? $container->load('getSylius_Repository_AdminUserService')), ($container->services['sylius.admin_user.token_generator.password_reset'] ?? $container->load('getSylius_AdminUser_TokenGenerator_PasswordResetService')), ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock()), $a), ['bus' => 'sylius.command_bus']);
    }
}
