<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uv_FUig_SyliusAdmin_Twig_Component_ProductVariant_FormdehydrateProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uv.fUig.sylius_admin.twig.component.product_variant.form::dehydrateProduct()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uv.fUig.sylius_admin.twig.component.product_variant.form::dehydrateProduct()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.uv.fUig.Sylius\\Component\\Core\\Model\\ProductInterface', NULL, 'Cannot autowire service ".service_locator.uv.fUig": it references interface "Sylius\\Component\\Core\\Model\\ProductInterface" but no such service exists. Did you create an instantiable class that implements this interface?'],
        ], [
            'product' => 'Sylius\\Component\\Core\\Model\\ProductInterface',
        ]))->withContext('sylius_admin.twig.component.product_variant.form::dehydrateProduct()', $container);
    }
}
