<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ByBweevService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.ByBweev' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/CommandHandler/UpdateCatalogPromotionStateHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/Processor/CatalogPromotionStateProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/Processor/CatalogPromotionStateProcessor.php';

        $a = ($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container));

        if (isset($container->privates['.messenger.handler_descriptor.ByBweev'])) {
            return $container->privates['.messenger.handler_descriptor.ByBweev'];
        }

        return $container->privates['.messenger.handler_descriptor.ByBweev'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Sylius\Bundle\CoreBundle\CatalogPromotion\CommandHandler\UpdateCatalogPromotionStateHandler(new \Sylius\Bundle\CoreBundle\CatalogPromotion\Processor\CatalogPromotionStateProcessor(($container->privates['sylius.checker.catalog_promotion_eligibility'] ?? $container->load('getSylius_Checker_CatalogPromotionEligibilityService')), $a), ($container->services['sylius.repository.catalog_promotion'] ?? $container->load('getSylius_Repository_CatalogPromotionService'))), ['bus' => 'sylius.command_bus']);
    }
}
