<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributesOperationRouteFactoryInterface2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.Sylius\Resource\Symfony\Routing\Factory\AttributesOperationRouteFactoryInterface' shared service.
     *
     * @return \Sylius\Resource\Symfony\Routing\Factory\AttributesOperationRouteFactory
     *
     * @deprecated Since sylius/resource-bundle 1.13: The ".container.private.Sylius\Resource\Symfony\Routing\Factory\AttributesOperationRouteFactoryInterface" service is deprecated since sylius/resource-bundle 1.13 and will be removed in sylius/resource-bundle 2.0. Use "sylius.routing.resource.route_collection_factory" instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('sylius/resource-bundle', '1.13', 'The ".container.private.Sylius\\Resource\\Symfony\\Routing\\Factory\\AttributesOperationRouteFactoryInterface" service is deprecated since sylius/resource-bundle 1.13 and will be removed in sylius/resource-bundle 2.0. Use "sylius.routing.resource.route_collection_factory" instead.');

        return $container->services['.container.private.Sylius\\Resource\\Symfony\\Routing\\Factory\\AttributesOperationRouteFactoryInterface'] = new \Sylius\Resource\Symfony\Routing\Factory\AttributesOperationRouteFactory(($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container)), ($container->services['Sylius\\Resource\\Symfony\\Routing\\Factory\\OperationRouteFactoryInterface'] ?? $container->load('getOperationRouteFactoryInterfaceService')), ($container->privates['sylius.resource_metadata_collection.factory.templates_dir'] ?? self::getSylius_ResourceMetadataCollection_Factory_TemplatesDirService($container)));
    }
}
