<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplyStateMachineTransitionProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Resource\StateMachine\State\ApplyStateMachineTransitionProcessor' shared service.
     *
     * @return \Sylius\Resource\StateMachine\State\ApplyStateMachineTransitionProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/StateMachine/State/ApplyStateMachineTransitionProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/StateMachine/OperationStateMachineInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/StateMachine/OperationStateMachine.php';

        return $container->privates['Sylius\\Resource\\StateMachine\\State\\ApplyStateMachineTransitionProcessor'] = new \Sylius\Resource\StateMachine\State\ApplyStateMachineTransitionProcessor(new \Sylius\Resource\StateMachine\OperationStateMachine(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'symfony' => ['privates', 'sylius.state_machine.operation.symfony', 'getSylius_StateMachine_Operation_SymfonyService', true],
            'winzou' => ['privates', 'sylius.state_machine.operation.winzou', 'getSylius_StateMachine_Operation_WinzouService', true],
        ], [
            'symfony' => 'Sylius\\Resource\\Symfony\\Workflow\\OperationStateMachine',
            'winzou' => 'Sylius\\Resource\\Winzou\\StateMachine\\OperationStateMachine',
        ])), ($container->privates['Sylius\\Resource\\Doctrine\\Common\\State\\PersistProcessor'] ?? $container->load('getPersistProcessorService')));
    }
}
