<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Messenger_ExecuteCommandHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'console.messenger.execute_command_handler' shared service.
     *
     * @return \Symfony\Component\Console\Messenger\RunCommandMessageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Messenger/RunCommandMessageHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Application.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Console/Application.php';

        $a = new \Symfony\Bundle\FrameworkBundle\Console\Application(($container->services['kernel'] ?? $container->get('kernel', 1)));
        $a->setAutoExit(false);

        return $container->privates['console.messenger.execute_command_handler'] = new \Symfony\Component\Console\Messenger\RunCommandMessageHandler($a);
    }
}
