<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_SyliusMollie_Console_Command_Subscription_BeginProcessingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.sylius_mollie.console.command.subscription.begin_processing' shared service.
     *
     * @return \Sylius\MolliePlugin\Console\Command\BeginProcessingSubscriptions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Console/Command/BeginProcessingSubscriptions.php';

        return $container->services['console.command.public_alias.sylius_mollie.console.command.subscription.begin_processing'] = new \Sylius\MolliePlugin\Console\Command\BeginProcessingSubscriptions(($container->services['sylius_mollie.repository.mollie_subscription'] ?? $container->load('getSyliusMollie_Repository_MollieSubscriptionService')), ($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container)));
    }
}
