<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_RoutableMessageBusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.routable_message_bus' shared service.
     *
     * @return \Symfony\Component\Messenger\RoutableMessageBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/RoutableMessageBus.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['messenger.routable_message_bus'])) {
            return $container->privates['messenger.routable_message_bus'];
        }

        return $container->privates['messenger.routable_message_bus'] = new \Symfony\Component\Messenger\RoutableMessageBus(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sylius.payment_request.command_bus' => ['privates', 'debug.traced.sylius.payment_request.command_bus', 'getDebug_Traced_Sylius_PaymentRequest_CommandBusService', false],
            'sylius.command_bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
            'sylius.query_bus' => ['privates', 'debug.traced.sylius.query_bus', 'getDebug_Traced_Sylius_QueryBusService', false],
            'sylius.event_bus' => ['privates', 'debug.traced.sylius.event_bus', 'getDebug_Traced_Sylius_EventBusService', false],
        ], [
            'sylius.payment_request.command_bus' => '?',
            'sylius.command_bus' => '?',
            'sylius.query_bus' => '?',
            'sylius.event_bus' => '?',
        ]), $a);
    }
}
