<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uv.fUig.Sylius\Component\Core\Model\ProductInterface' shared service.
     *
     * @return \Sylius\Component\Core\Model\ProductInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uv.fUig": it references interface "Sylius\\Component\\Core\\Model\\ProductInterface" but no such service exists. Did you create an instantiable class that implements this interface?');
    }
}
