<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentRequestRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\PaymentBundle\Doctrine\ORM\PaymentRequestRepository' shared service.
     *
     * @return \Sylius\Bundle\PaymentBundle\Doctrine\ORM\PaymentRequestRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Payment/Repository/PaymentRequestRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Doctrine/ORM/PaymentRequestRepository.php';

        return $container->privates['Sylius\\Bundle\\PaymentBundle\\Doctrine\\ORM\\PaymentRequestRepository'] = $container->get('sylius.repository.payment_request');
    }
}
