<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductOptionTranslationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductOptionTranslationRepository' shared service.
     *
     * @return \Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductOptionTranslationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Repository/ProductOptionTranslationRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductOptionTranslationRepository.php';

        return $container->privates['Sylius\\Bundle\\ProductBundle\\Doctrine\\ORM\\ProductOptionTranslationRepository'] = $container->get('sylius.repository.product_option_translation');
    }
}
