<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResponderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Resource\Symfony\Request\State\Responder' shared service.
     *
     * @return \Sylius\Resource\Symfony\Request\State\Responder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/State/ResponderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Request/State/Responder.php';

        $a = ($container->privates['.service_locator.bCqMR.9'] ?? $container->load('get_ServiceLocator_BCqMR_9Service'));

        if (isset($container->privates['Sylius\\Resource\\Symfony\\Request\\State\\Responder'])) {
            return $container->privates['Sylius\\Resource\\Symfony\\Request\\State\\Responder'];
        }

        return $container->privates['Sylius\\Resource\\Symfony\\Request\\State\\Responder'] = new \Sylius\Resource\Symfony\Request\State\Responder($a);
    }
}
