<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Form_Type_CatalogPromotionScope_ForVariantsScopeConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_admin.form.type.catalog_promotion_scope.for_variants_scope_configuration' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Form\Type\CatalogPromotionScope\ForVariantsScopeConfigurationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Form/Type/CatalogPromotionScope/ForVariantsScopeConfigurationType.php';

        return $container->privates['sylius_admin.form.type.catalog_promotion_scope.for_variants_scope_configuration'] = new \Sylius\Bundle\AdminBundle\Form\Type\CatalogPromotionScope\ForVariantsScopeConfigurationType(($container->privates['sylius.form.type.data_transformer.product_variants_to_codes'] ?? $container->load('getSylius_Form_Type_DataTransformer_ProductVariantsToCodesService')));
    }
}
