<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_StateProvider_Admin_OrderItem_Adjustment_CollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.state_provider.admin.order_item.adjustment.collection' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\StateProvider\Common\Adjustment\CollectionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/StateProvider/Common/Adjustment/CollectionProvider.php';

        $a = ($container->services['sylius.repository.order_item'] ?? $container->load('getSylius_Repository_OrderItemService'));

        if (isset($container->privates['sylius_api.state_provider.admin.order_item.adjustment.collection'])) {
            return $container->privates['sylius_api.state_provider.admin.order_item.adjustment.collection'];
        }

        return $container->privates['sylius_api.state_provider.admin.order_item.adjustment.collection'] = new \Sylius\Bundle\ApiBundle\StateProvider\Common\Adjustment\CollectionProvider($a, 'id');
    }
}
