<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_CatalogPromotionScope_ForProductsScopeConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.form.type.catalog_promotion_scope.for_products_scope_configuration' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Form\Type\CatalogPromotionScope\ForProductsScopeConfigurationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Form/Type/CatalogPromotionScope/ForProductsScopeConfigurationType.php';

        return $container->privates['sylius.form.type.catalog_promotion_scope.for_products_scope_configuration'] = new \Sylius\Bundle\CoreBundle\Form\Type\CatalogPromotionScope\ForProductsScopeConfigurationType(($container->privates['sylius.form.type.data_transformer.products_to_codes'] ?? $container->load('getSylius_Form_Type_DataTransformer_ProductsToCodesService')));
    }
}
