<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Order_History_Content_Sections_Addresses_BillingAddress_Details_Data_Hookable_FirstNameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.order.history.content.sections.addresses.billing_address.details.data.hookable.first_name' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.order.history.content.sections.addresses.billing_address.details.data.hookable.first_name'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.order.history.content.sections.addresses.billing_address.details.data', 'first_name', '@SyliusAdmin/order/history/common/sections/addresses/address/details/data/first_name.html.twig', [], [], 900, true);
    }
}
