<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusMollie_Admin_PaymentLink_Create_Content_Form_Sections_General_Hookable_MethodsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_mollie.admin.payment_link.create.content.form.sections.general.hookable.methods' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_mollie.admin.payment_link.create.content.form.sections.general.hookable.methods'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_mollie.admin.payment_link.create.content.form.sections.general', 'methods', '@SyliusMolliePlugin/admin/payment_link/form/sections/general/methods.html.twig', [], [], 0, true);
    }
}
