<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_ApplePay_Resolver_ApplePayDirectApiPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.apple_pay.resolver.apple_pay_direct_api_payment' shared service.
     *
     * @return \Sylius\MolliePlugin\ApplePay\Resolver\ApplePayDirectApiPaymentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/ApplePay/Resolver/ApplePayDirectApiPaymentResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/ApplePay/Resolver/ApplePayDirectApiPaymentResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/mollie/mollie-api-php/src/MollieApiClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Client/MollieApiClient.php';

        return $container->services['sylius_mollie.apple_pay.resolver.apple_pay_direct_api_payment'] = new \Sylius\MolliePlugin\ApplePay\Resolver\ApplePayDirectApiPaymentResolver(($container->services['sylius_mollie.client.mollie_api'] ??= new \Sylius\MolliePlugin\Client\MollieApiClient()), ($container->services['sylius_mollie.resolver.mollie_api_client_key'] ?? $container->load('getSyliusMollie_Resolver_MollieApiClientKeyService')), ($container->services['sylius_mollie.apple_pay.provider.order_payment_apple_pay_direct'] ?? $container->load('getSyliusMollie_ApplePay_Provider_OrderPaymentApplePayDirectService')));
    }
}
