<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusShop_Form_Type_Checkout_SelectPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_shop.form.type.checkout.select_payment' shared service.
     *
     * @return \Sylius\Bundle\ShopBundle\Form\Type\Checkout\SelectPaymentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Form/Type/Checkout/SelectPaymentType.php';

        return $container->privates['sylius_shop.form.type.checkout.select_payment'] = new \Sylius\Bundle\ShopBundle\Form\Type\Checkout\SelectPaymentType();
    }
}
