<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Validator_ApplePayDirect_PaymentMethodCheckoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.validator.apple_pay_direct.payment_method_checkout' shared service.
     *
     * @return \Sylius\MolliePlugin\Validator\Constraints\PaymentMethodCheckoutValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Validator/Constraints/PaymentMethodCheckoutValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Payum/Checker/MollieGatewayFactoryCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Payum/Checker/MollieGatewayFactoryChecker.php';

        return $container->services['sylius_mollie.validator.apple_pay_direct.payment_method_checkout'] = new \Sylius\MolliePlugin\Validator\Constraints\PaymentMethodCheckoutValidator(($container->services['sylius_mollie.resolver.order.payment_checkout_order'] ?? $container->load('getSyliusMollie_Resolver_Order_PaymentCheckoutOrderService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['sylius_mollie.payum.checker.mollie_gateway_factory'] ??= new \Sylius\MolliePlugin\Payum\Checker\MollieGatewayFactoryChecker()));
    }
}
