<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_Workflow_Order_AssignOrderTokenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.listener.workflow.order.assign_order_token' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\AssignOrderTokenListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/Workflow/Order/AssignOrderTokenListener.php';

        return $container->privates['sylius.listener.workflow.order.assign_order_token'] = new \Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\AssignOrderTokenListener(($container->services['sylius.assigner.order_token.unique_id_based'] ?? $container->load('getSylius_Assigner_OrderToken_UniqueIdBasedService')));
    }
}
