<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusShop_Twig_Component_Product_CardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_shop.twig.component.product.card' service.
     *
     * @return \Sylius\Bundle\ShopBundle\Twig\Component\Product\CardComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Twig/Component/HookableComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Twig/Component/Product/CardComponent.php';

        $container->factories['service_container']['sylius_shop.twig.component.product.card'] = function ($container) {
            return new \Sylius\Bundle\ShopBundle\Twig\Component\Product\CardComponent(($container->services['sylius.repository.product'] ?? $container->load('getSylius_Repository_ProductService')), ($container->services['sylius.resolver.product_variant'] ?? self::getSylius_Resolver_ProductVariantService($container)), ($container->services['sylius.context.channel'] ?? self::getSylius_Context_ChannelService($container)), ($container->services['sylius.context.locale'] ?? self::getSylius_Context_LocaleService($container)), ($container->privates['sylius.calculator.product_variant_price'] ?? self::getSylius_Calculator_ProductVariantPriceService($container)));
        };

        return $container->factories['service_container']['sylius_shop.twig.component.product.card']($container);
    }
}
