<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Repository_ProductAssociationTypeTranslationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.repository.product_association_type_translation' shared service.
     *
     * @return \Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductAssociationTypeTranslationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Repository/ProductAssociationTypeTranslationRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAssociationTypeTranslationRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius.repository.product_association_type_translation'])) {
            return $container->services['sylius.repository.product_association_type_translation'];
        }

        return $container->services['sylius.repository.product_association_type_translation'] = new \Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductAssociationTypeTranslationRepository($a, $a->getClassMetadata('App\\Entity\\Product\\ProductAssociationTypeTranslation'));
    }
}
