<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Checkout_Address_Content_Form_AddressesbillingRequired_Hookable_DifferentShippingAddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.checkout.address.content.form.addresses#billing_required.hookable.different_shipping_address' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.checkout.address.content.form.addresses#billing_required.hookable.different_shipping_address'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_shop.checkout.address.content.form.addresses#billing_required', 'different_shipping_address', '@SyliusShop/checkout/address/content/form/addresses/different_address.html.twig', [], ['type' => 'shipping', 'field' => 'differentShippingAddress'], 100, true);
    }
}
