<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_PromotionCoupon_Update_Content_Form_Sectionsright_Hookable_ConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.promotion_coupon.update.content.form.sections#right.hookable.configuration' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.promotion_coupon.update.content.form.sections#right.hookable.configuration'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.promotion_coupon.update.content.form.sections#right', 'configuration', '@SyliusAdmin/promotion_coupon/form/sections/configuration.html.twig', [], [], 0, true);
    }
}
