<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSenderDataDumperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\MailerBundle\Console\Command\Dumper\SenderDataDumper' shared service.
     *
     * @return \Sylius\Bundle\MailerBundle\Console\Command\Dumper\SenderDataDumper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mailer-bundle/src/Bundle/Console/Command/Dumper/DumperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mailer-bundle/src/Bundle/Console/Command/Dumper/SenderDataDumper.php';

        return $container->services['Sylius\\Bundle\\MailerBundle\\Console\\Command\\Dumper\\SenderDataDumper'] = new \Sylius\Bundle\MailerBundle\Console\Command\Dumper\SenderDataDumper('Example.com', 'no-reply@example.com');
    }
}
