<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Voucher_Updater_OrderVoucherAdjustmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.voucher.updater.order_voucher_adjustment' shared service.
     *
     * @return \Sylius\MolliePlugin\Voucher\Updater\OrderVoucherAdjustmentUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Voucher/Updater/OrderVoucherAdjustmentUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Voucher/Updater/OrderVoucherAdjustmentUpdater.php';

        return $container->services['sylius_mollie.voucher.updater.order_voucher_adjustment'] = new \Sylius\MolliePlugin\Voucher\Updater\OrderVoucherAdjustmentUpdater(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['sylius_mollie.voucher.applicator.order_vouchers'] ?? $container->load('getSyliusMollie_Voucher_Applicator_OrderVouchersService')), ($container->services['sylius_mollie.provider.divisor'] ??= new \Sylius\MolliePlugin\Provider\DivisorProvider()));
    }
}
