<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusPaypal_Controller_Webhook_RefundOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_paypal.controller.webhook.refund_order' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\Webhook\RefundOrderAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/Webhook/RefundOrderAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PayPalRefundDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PayPalRefundDataProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/GenericApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/GenericApi.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/RequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/ServerRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/StreamFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UploadedFileFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-factory/src/UriFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/php-http/discovery/src/Psr17Factory.php';

        return $container->services['sylius_paypal.controller.webhook.refund_order'] = new \Sylius\PayPalPlugin\Controller\Webhook\RefundOrderAction(($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container)), ($container->privates['sylius_paypal.provider.payment'] ?? $container->load('getSyliusPaypal_Provider_PaymentService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \Sylius\PayPalPlugin\Provider\PayPalRefundDataProvider(($container->privates['sylius_paypal.api.cache_authorize_client'] ?? $container->load('getSyliusPaypal_Api_CacheAuthorizeClientService')), new \Sylius\PayPalPlugin\Api\GenericApi(($container->privates['psr18.http_client'] ?? $container->load('getPsr18_HttpClientService')), ($container->privates['http_discovery.psr17_factory'] ??= new \Http\Discovery\Psr17Factory())), ($container->privates['sylius_paypal.provider.paypal_payment_method'] ?? $container->load('getSyliusPaypal_Provider_PaypalPaymentMethodService'))));
    }
}
