<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Provider_Statistics_OrdersTotals_DayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.provider.statistics.orders_totals.day' shared service.
     *
     * @return \Sylius\Component\Core\Statistics\Provider\OrdersTotals\DayBasedOrdersTotalProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/SalesProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/OrdersTotals/OrdersTotalsProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/OrdersTotals/DayBasedOrdersTotalProvider.php';

        return $container->privates['sylius.provider.statistics.orders_totals.day'] = new \Sylius\Component\Core\Statistics\Provider\OrdersTotals\DayBasedOrdersTotalProvider(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)));
    }
}
