<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Repository_ZoneMemberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.repository.zone_member' shared service.
     *
     * @return \Sylius\Bundle\AddressingBundle\Doctrine\ORM\ZoneMemberRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Repository/ZoneMemberRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AddressingBundle/Doctrine/ORM/ZoneMemberRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius.repository.zone_member'])) {
            return $container->services['sylius.repository.zone_member'];
        }

        return $container->services['sylius.repository.zone_member'] = new \Sylius\Bundle\AddressingBundle\Doctrine\ORM\ZoneMemberRepository($a, $a->getClassMetadata('App\\Entity\\Addressing\\ZoneMember'));
    }
}
