<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Controller_Admin_RefundService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.controller.admin.refund' shared service.
     *
     * @return \Sylius\MolliePlugin\Controller\Admin\RefundAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Controller/Admin/RefundAction.php';

        return $container->services['sylius_mollie.controller.admin.refund'] = new \Sylius\MolliePlugin\Controller\Admin\RefundAction(($container->services['sylius.repository.payment'] ?? $container->load('getSylius_Repository_PaymentService')), ($container->services['payum'] ?? $container->load('getPayumService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sylius_mollie.logger.mollie_logger_action'] ?? $container->load('getSyliusMollie_Logger_MollieLoggerActionService')));
    }
}
