<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Product_GenerateVariants_Content_Header_Hookable_BreadcrumbsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product.generate_variants.content.header.hookable.breadcrumbs' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product.generate_variants.content.header.hookable.breadcrumbs'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.product.generate_variants.content.header', 'breadcrumbs', '@SyliusAdmin/product/generate_variants/header/breadcrumbs.html.twig', [], [], 100, true);
    }
}
