<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_StateProcessor_Shop_Address_PersistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.state_processor.shop.address.persist' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\StateProcessor\Shop\Address\PersistProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/StateProcessor/Shop/Address/PersistProcessor.php';

        return $container->privates['sylius_api.state_processor.shop.address.persist'] = new \Sylius\Bundle\ApiBundle\StateProcessor\Shop\Address\PersistProcessor(($container->privates['api_platform.doctrine.orm.state.persist_processor'] ?? $container->load('getApiPlatform_Doctrine_Orm_State_PersistProcessorService')), ($container->privates['sylius_api.context.user.token_based'] ?? self::getSyliusApi_Context_User_TokenBasedService($container)));
    }
}
