<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Homepage_Index_Hookable_LatestDealsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.homepage.index.hookable.latest_deals' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.homepage.index.hookable.latest_deals'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_shop.homepage.index', 'latest_deals', 'sylius_shop:product:list', ['limit' => 4, 'template' => '@SyliusShop/product/common/list.html.twig'], [], ['title' => 'sylius.homepage.latest_deals', 'test_attribute' => 'latest-deals'], 200, true);
    }
}
