<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Resolver_ApiKeysTestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.resolver.api_keys_test' shared service.
     *
     * @return \Sylius\MolliePlugin\Resolver\ApiKeysTestResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Resolver/ApiKeysTestResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Resolver/ApiKeysTestResolver.php';

        return $container->services['sylius_mollie.resolver.api_keys_test'] = new \Sylius\MolliePlugin\Resolver\ApiKeysTestResolver(($container->services['sylius_mollie.creator.api_keys_test'] ?? $container->load('getSyliusMollie_Creator_ApiKeysTestService')));
    }
}
