<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Factory_ZoneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.factory.zone' shared service.
     *
     * @return \Sylius\Component\Addressing\Factory\ZoneFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Factory/ZoneFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Factory/ZoneFactory.php';

        return $container->services['sylius.factory.zone'] = new \Sylius\Component\Addressing\Factory\ZoneFactory(new \Sylius\Resource\Factory\Factory('App\\Entity\\Addressing\\Zone'), ($container->services['sylius.factory.zone_member'] ??= new \Sylius\Resource\Factory\Factory('App\\Entity\\Addressing\\ZoneMember')));
    }
}
