<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_OpenApi_DocumentationModifier_ImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.open_api.documentation_modifier.image' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\OpenApi\Documentation\ImageDocumentationModifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/DocumentationModifierInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/ImageDocumentationModifier.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Provider/ImageFiltersProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Provider/LiipImageFiltersProvider.php';

        return $container->privates['sylius_api.open_api.documentation_modifier.image'] = new \Sylius\Bundle\ApiBundle\OpenApi\Documentation\ImageDocumentationModifier(new \Sylius\Bundle\ApiBundle\Provider\LiipImageFiltersProvider($container->parameters['liip_imagine.filter_sets']));
    }
}
