<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusPayum_Factory_PaymentRequest_PayumTokenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_payum.factory.payment_request.payum_token' shared service.
     *
     * @return \Sylius\Bundle\PayumBundle\PaymentRequest\Factory\PayumTokenFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/PaymentRequest/Factory/PayumTokenFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/PaymentRequest/Factory/PayumTokenFactory.php';

        $a = ($container->services['payum'] ?? $container->load('getPayumService'));

        if (isset($container->privates['sylius_payum.factory.payment_request.payum_token'])) {
            return $container->privates['sylius_payum.factory.payment_request.payum_token'];
        }

        return $container->privates['sylius_payum.factory.payment_request.payum_token'] = new \Sylius\Bundle\PayumBundle\PaymentRequest\Factory\PayumTokenFactory($a);
    }
}
