<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Account_ChangePassword_Update_Content_Main_Form_Fields_Hookable_ConfirmNewPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.account.change_password.update.content.main.form.fields.hookable.confirm_new_password' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.account.change_password.update.content.main.form.fields.hookable.confirm_new_password'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_shop.account.change_password.update.content.main.form.fields', 'confirm_new_password', '@SyliusShop/account/change_password/update/content/main/form/fields/confirm_new_password.html.twig', [], [], 0, true);
    }
}
