<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Calculator_CalculateTaxAmountService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.calculator.calculate_tax_amount' shared service.
     *
     * @return \Sylius\MolliePlugin\Calculator\CalculateTaxAmount
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Calculator/CalculateTaxAmountInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Calculator/CalculateTaxAmount.php';

        return $container->services['sylius_mollie.calculator.calculate_tax_amount'] = new \Sylius\MolliePlugin\Calculator\CalculateTaxAmount(($container->services['sylius_mollie.converter.int_to_string'] ?? $container->load('getSyliusMollie_Converter_IntToStringService')));
    }
}
