<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_TaxCalculatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.tax_calculator' shared service.
     *
     * @return \Sylius\Component\Taxation\Calculator\DelegatingCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxation/Calculator/CalculatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxation/Calculator/DelegatingCalculator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxation/Calculator/DefaultCalculator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxation/Calculator/DecimalCalculator.php';

        $a = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Component\\Taxation\\Calculator\\CalculatorInterface', 'Tax calculator');
        $a->register('default', new \Sylius\Component\Taxation\Calculator\DefaultCalculator());
        $a->register('decimal', new \Sylius\Component\Taxation\Calculator\DecimalCalculator());

        return $container->privates['sylius.tax_calculator'] = new \Sylius\Component\Taxation\Calculator\DelegatingCalculator($a);
    }
}
