<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Base_Header_Navbar_Hookable_MenuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.base.header.navbar.hookable.menu' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.base.header.navbar.hookable.menu'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_shop.base.header.navbar', 'menu', 'sylius_shop:common:taxon_menu', ['template' => '@SyliusShop/shared/layout/base/header/navbar/menu.html.twig'], [], [], 0, true);
    }
}
