<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Mapper_AddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_api.mapper.address' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Mapper\AddressMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Mapper/AddressMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Mapper/AddressMapper.php';

        return $container->services['sylius_api.mapper.address'] = new \Sylius\Bundle\ApiBundle\Mapper\AddressMapper();
    }
}
