<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Controller_Admin_ChangePositionPaymentMethodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.controller.admin.change_position_payment_method' shared service.
     *
     * @return \Sylius\MolliePlugin\Controller\Admin\ChangePositionPaymentMethodAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Controller/Admin/ChangePositionPaymentMethodAction.php';

        return $container->services['sylius_mollie.controller.admin.change_position_payment_method'] = new \Sylius\MolliePlugin\Controller\Admin\ChangePositionPaymentMethodAction(($container->services['sylius_mollie.updater.mollie_payment_method_position'] ?? $container->load('getSyliusMollie_Updater_MolliePaymentMethodPositionService')));
    }
}
