<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Applicator_OrderStateMachineTransitionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_api.applicator.order_state_machine_transition' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Applicator\OrderStateMachineTransitionApplicator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Applicator/OrderStateMachineTransitionApplicatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Applicator/OrderStateMachineTransitionApplicator.php';

        return $container->services['sylius_api.applicator.order_state_machine_transition'] = new \Sylius\Bundle\ApiBundle\Applicator\OrderStateMachineTransitionApplicator(($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container)));
    }
}
