<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Product_EnabledVariantsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.doctrine.orm.query_extension.shop.product.enabled_variants' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Doctrine\ORM\QueryExtension\Shop\Product\EnabledVariantsExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Extension/QueryCollectionExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Extension/QueryItemExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Product/EnabledVariantsExtension.php';

        return $container->privates['sylius_api.doctrine.orm.query_extension.shop.product.enabled_variants'] = new \Sylius\Bundle\ApiBundle\Doctrine\ORM\QueryExtension\Shop\Product\EnabledVariantsExtension(($container->privates['sylius.section_resolver.uri_based'] ?? self::getSylius_SectionResolver_UriBasedService($container)));
    }
}
