<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusShop_Twig_Component_Account_ChangePasswordFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_shop.twig.component.account.change_password_form' service.
     *
     * @return \Sylius\Bundle\ShopBundle\Twig\Component\Account\ChangePasswordFormComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentWithFormTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/LiveComponent/HookableLiveComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/TemplatePropTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Twig/Component/Account/ChangePasswordFormComponent.php';

        $container->factories['sylius_shop.twig.component.account.change_password_form'] = function ($container) {
            $a = ($container->services['form.factory'] ?? self::getForm_FactoryService($container));

            if (isset($container->services['sylius_shop.twig.component.account.change_password_form'])) {
                return $container->services['sylius_shop.twig.component.account.change_password_form'];
            }

            return new \Sylius\Bundle\ShopBundle\Twig\Component\Account\ChangePasswordFormComponent($a, 'Sylius\\Bundle\\ShopBundle\\Form\\Type\\UserChangePasswordType');
        };

        return $container->factories['sylius_shop.twig.component.account.change_password_form']($container);
    }
}
