<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Validator_HasEnabledEntityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.validator.has_enabled_entity' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Validator\Constraints\HasEnabledEntityValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasEnabledEntityValidator.php';

        return $container->privates['sylius.validator.has_enabled_entity'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\HasEnabledEntityValidator(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)));
    }
}
