<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusPaypal_Resolver_CapturePaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_paypal.resolver.capture_payment' shared service.
     *
     * @return \Sylius\PayPalPlugin\Resolver\CapturePaymentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Resolver/CapturePaymentResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Resolver/CapturePaymentResolver.php';

        return $container->privates['sylius_paypal.resolver.capture_payment'] = new \Sylius\PayPalPlugin\Resolver\CapturePaymentResolver(($container->services['payum'] ?? $container->load('getPayumService')));
    }
}
