<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Fixture_ExampleFactory_CatalogPromotionActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.fixture.example_factory.catalog_promotion_action' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Fixture\Factory\CatalogPromotionActionExampleFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionActionExampleFactory.php';

        return $container->services['sylius.fixture.example_factory.catalog_promotion_action'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\CatalogPromotionActionExampleFactory(($container->services['sylius.factory.catalog_promotion_action'] ??= new \Sylius\Resource\Factory\Factory('App\\Entity\\Promotion\\CatalogPromotionAction')));
    }
}
