<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Resolver_CustomerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.resolver.customer' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Resolver\CustomerResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resolver/CustomerResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resolver/CustomerResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Provider/CustomerProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Provider/CustomerProvider.php';

        return $container->services['sylius.resolver.customer'] = new \Sylius\Bundle\CoreBundle\Resolver\CustomerResolver(($container->services['sylius.factory.customer'] ??= new \Sylius\Resource\Factory\Factory('App\\Entity\\Customer\\Customer')), new \Sylius\Bundle\CoreBundle\Provider\CustomerProvider(($container->services['sylius.repository.customer'] ?? $container->load('getSylius_Repository_CustomerService')), ($container->privates['sylius.canonicalizer'] ??= new \Sylius\Component\User\Canonicalizer\Canonicalizer())));
    }
}
