<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Controller_GetTaxonBySlugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_api.controller.get_taxon_by_slug' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Controller\GetTaxonBySlugAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Controller/GetTaxonBySlugAction.php';

        return $container->services['sylius_api.controller.get_taxon_by_slug'] = new \Sylius\Bundle\ApiBundle\Controller\GetTaxonBySlugAction(($container->services['sylius.context.locale'] ?? self::getSylius_Context_LocaleService($container)), ($container->services['sylius.repository.taxon'] ?? $container->load('getSylius_Repository_TaxonService')), ($container->privates['sylius_api.api_platform.routing.iri_converter'] ?? self::getSyliusApi_ApiPlatform_Routing_IriConverterService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
