<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Console_Command_InformAboutGusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.console.command.inform_about_gus' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Console\Command\InformAboutGUSCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Console/Command/InformAboutGUSCommand.php';

        $container->services['sylius.console.command.inform_about_gus'] = $instance = new \Sylius\Bundle\CoreBundle\Console\Command\InformAboutGUSCommand();

        $instance->setName('sylius:inform-about-gus');
        $instance->setDescription('Informs about Sylius internal statistical service.');

        return $instance;
    }
}
