<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Processor_OrderPay_RouteParametersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.processor.order_pay.route_parameters' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\OrderPay\Processor\RouteParametersProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/OrderPay/Processor/RouteParametersProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/OrderPay/Processor/RouteParametersProcessor.php';

        return $container->privates['sylius.processor.order_pay.route_parameters'] = new \Sylius\Bundle\CoreBundle\OrderPay\Processor\RouteParametersProcessor(new \Symfony\Component\ExpressionLanguage\ExpressionLanguage(), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
