<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Provider_PaymentRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.provider.payment_request' shared service.
     *
     * @return \Sylius\Bundle\PaymentBundle\Provider\PaymentRequestProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/PaymentRequestProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/PaymentRequestProvider.php';

        return $container->privates['sylius.provider.payment_request'] = new \Sylius\Bundle\PaymentBundle\Provider\PaymentRequestProvider(($container->services['sylius.repository.payment_request'] ?? $container->load('getSylius_Repository_PaymentRequestService')));
    }
}
