<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_StateProvider_Shop_Product_ProductAttributeValue_CollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.state_provider.shop.product.product_attribute_value.collection' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\StateProvider\Shop\Product\ProductAttributeValue\CollectionProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/StateProvider/Shop/Product/ProductAttributeValue/CollectionProvider.php';

        $a = ($container->services['sylius.repository.product_attribute_value'] ?? $container->load('getSylius_Repository_ProductAttributeValueService'));

        if (isset($container->privates['sylius_api.state_provider.shop.product.product_attribute_value.collection'])) {
            return $container->privates['sylius_api.state_provider.shop.product.product_attribute_value.collection'];
        }

        return $container->privates['sylius_api.state_provider.shop.product.product_attribute_value.collection'] = new \Sylius\Bundle\ApiBundle\StateProvider\Shop\Product\ProductAttributeValue\CollectionProvider(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sylius_api.doctrine.orm.query_extension.common.non_archived'] ??= new \Sylius\Bundle\ApiBundle\Doctrine\ORM\QueryExtension\Common\NonArchivedExtension());
            yield 1 => ($container->privates['sylius_api.doctrine.orm.query_extension.common.translation_order_locale'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Common_TranslationOrderLocaleService'));
            yield 2 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.product_review.accepted'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_ProductReview_AcceptedService'));
            yield 3 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.address.shop_user_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Address_ShopUserBasedService'));
            yield 4 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.product.channel_and_locale_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Product_ChannelAndLocaleBasedService'));
            yield 5 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.product.enabled_variants'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Product_EnabledVariantsService'));
            yield 6 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.product.taxon_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Product_TaxonBasedService'));
            yield 7 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.order.channel_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Order_ChannelBasedService'));
            yield 8 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.order_item.visitor_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_OrderItem_VisitorBasedService'));
            yield 9 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.order_item.shop_user_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_OrderItem_ShopUserBasedService'));
            yield 10 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.country.channel_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Country_ChannelBasedService'));
            yield 11 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.taxon.channel_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Taxon_ChannelBasedService'));
            yield 12 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.currency.channel_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Currency_ChannelBasedService'));
            yield 13 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.locale.channel_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Locale_ChannelBasedService'));
            yield 14 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.order.shop_user_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Order_ShopUserBasedService'));
            yield 15 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.order.state_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Order_StateBasedService'));
            yield 16 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.common.enabled'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Common_EnabledService'));
            yield 17 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.exchange_rate.channel_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_ExchangeRate_ChannelBasedService'));
            yield 18 => ($container->privates['sylius_api.doctrine.orm.query_extension.admin.order.state_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Admin_Order_StateBasedService'));
            yield 19 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.product.enabled_within_product_association'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Product_EnabledWithinProductAssociationService'));
            yield 20 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.shipping_method.channel_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_ShippingMethod_ChannelBasedService'));
            yield 21 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.shipping_method.enabled'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_ShippingMethod_EnabledService'));
            yield 22 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.payment_method.channel_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_PaymentMethod_ChannelBasedService'));
            yield 23 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.payment_method.enabled'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_PaymentMethod_EnabledService'));
            yield 24 => ($container->privates['sylius_api.doctrine.orm.query_extension.shop.customer.shop_user_based'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Customer_ShopUserBasedService'));
            yield 25 => ($container->privates['api_platform.doctrine.orm.query_extension.filter'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_FilterService'));
            yield 26 => ($container->privates['api_platform.doctrine.orm.extension.parameter_extension'] ?? $container->load('getApiPlatform_Doctrine_Orm_Extension_ParameterExtensionService'));
            yield 27 => ($container->privates['sylius_api.doctrine.orm.query_extension.common.filter_eager_loading'] ?? $container->load('getSyliusApi_Doctrine_Orm_QueryExtension_Common_FilterEagerLoadingService'));
            yield 28 => ($container->privates['api_platform.doctrine.orm.query_extension.eager_loading'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_EagerLoadingService'));
            yield 29 => ($container->privates['api_platform.doctrine.orm.query_extension.order'] ??= new \ApiPlatform\Doctrine\Orm\Extension\OrderExtension('ASC'));
            yield 30 => ($container->privates['api_platform.doctrine.orm.query_extension.pagination'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_PaginationService'));
        }, 31), ($container->privates['sylius.section_resolver.uri_based'] ?? self::getSylius_SectionResolver_UriBasedService($container)), $a, ($container->services['sylius.context.locale'] ?? self::getSylius_Context_LocaleService($container)), ($container->privates['sylius.provider.locale.channel_based'] ?? self::getSylius_Provider_Locale_ChannelBasedService($container)), 'fr_FR');
    }
}
