<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Factory_DatePeriodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.factory.date_period' shared service.
     *
     * @return \Sylius\MolliePlugin\Factory\DatePeriodFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Factory/DatePeriodFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Factory/DatePeriodFactory.php';

        return $container->services['sylius_mollie.factory.date_period'] = new \Sylius\MolliePlugin\Factory\DatePeriodFactory();
    }
}
