<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Fixture_ExampleFactory_CatalogPromotionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.fixture.example_factory.catalog_promotion' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Fixture\Factory\CatalogPromotionExampleFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/CatalogPromotionExampleFactory.php';

        return $container->services['sylius.fixture.example_factory.catalog_promotion'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\CatalogPromotionExampleFactory(($container->services['sylius.factory.catalog_promotion'] ??= new \Sylius\Resource\Factory\Factory('App\\Entity\\Promotion\\CatalogPromotion')), ($container->services['sylius.repository.locale'] ?? self::getSylius_Repository_LocaleService($container)), ($container->services['sylius.repository.channel'] ?? self::getSylius_Repository_ChannelService($container)), ($container->services['sylius.fixture.example_factory.catalog_promotion_scope'] ?? $container->load('getSylius_Fixture_ExampleFactory_CatalogPromotionScopeService')), ($container->services['sylius.fixture.example_factory.catalog_promotion_action'] ?? $container->load('getSylius_Fixture_ExampleFactory_CatalogPromotionActionService')));
    }
}
