<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_CatalogPromotion_Show_Content_Sections_Actions_ActionpercentageDiscount_Hookable_AmountService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.catalog_promotion.show.content.sections.actions.action#percentage_discount.hookable.amount' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.catalog_promotion.show.content.sections.actions.action#percentage_discount.hookable.amount'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.catalog_promotion.show.content.sections.actions.action#percentage_discount', 'amount', '@SyliusAdmin/catalog_promotion/show/content/sections/actions/action/amount.html.twig', [], [], 0, true);
    }
}
