<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Twig_Component_Taxon_DeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.twig.component.taxon.delete' service.
     *
     * @return \Sylius\Bundle\AdminBundle\Twig\Component\Taxon\DeleteComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/LiveComponent/HookableLiveComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentToolsTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/TemplatePropTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/Component/Taxon/DeleteComponent.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/LiveResponder.php';

        $container->factories['sylius_admin.twig.component.taxon.delete'] = function ($container) {
            $instance = new \Sylius\Bundle\AdminBundle\Twig\Component\Taxon\DeleteComponent(($container->services['security.csrf.token_manager'] ?? self::getSecurity_Csrf_TokenManagerService($container)));

            $instance->setLiveResponder(($container->privates['ux.live_component.live_responder'] ??= new \Symfony\UX\LiveComponent\LiveResponder()));

            return $instance;
        };

        return $container->factories['sylius_admin.twig.component.taxon.delete']($container);
    }
}
