<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Validator_ChangedItemQuantityInCartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.validator.changed_item_quantity_in_cart' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Validator\Constraints\ChangedItemQuantityInCartValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChangedItemQuantityInCartValidator.php';

        return $container->privates['sylius_api.validator.changed_item_quantity_in_cart'] = new \Sylius\Bundle\ApiBundle\Validator\Constraints\ChangedItemQuantityInCartValidator(($container->services['sylius.repository.order_item'] ?? $container->load('getSylius_Repository_OrderItemService')), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->privates['sylius.checker.inventory.availability'] ??= new \Sylius\Component\Inventory\Checker\AvailabilityChecker()));
    }
}
