<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusMollie_Admin_EmailTemplate_Create_Content_Form_Sections_General_Translations_Hookable_ContentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_mollie.admin.email_template.create.content.form.sections.general.translations.hookable.content' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_mollie.admin.email_template.create.content.form.sections.general.translations.hookable.content'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_mollie.admin.email_template.create.content.form.sections.general.translations', 'content', '@SyliusMolliePlugin/admin/email_template/form/sections/general/translations/content.html.twig', [], [], 0, true);
    }
}
