<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Twig_Component_Dashboard_NewOrdersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.twig.component.dashboard.new_orders' service.
     *
     * @return \Sylius\Bundle\AdminBundle\Twig\Component\Dashboard\NewOrdersComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/LiveComponent/HookableLiveComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/TemplatePropTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/Component/Dashboard/NewOrdersComponent.php';

        $container->factories['sylius_admin.twig.component.dashboard.new_orders'] = function ($container) {
            return new \Sylius\Bundle\AdminBundle\Twig\Component\Dashboard\NewOrdersComponent(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['sylius.repository.channel'] ?? self::getSylius_Repository_ChannelService($container)));
        };

        return $container->factories['sylius_admin.twig.component.dashboard.new_orders']($container);
    }
}
