<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Factory_ProductOptionValueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.factory.product_option_value' shared service.
     *
     * @return \Sylius\Resource\Factory\TranslatableFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Factory/TranslatableFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Factory/TranslatableFactory.php';

        return $container->services['sylius.factory.product_option_value'] = new \Sylius\Resource\Factory\TranslatableFactory(new \Sylius\Resource\Factory\Factory('App\\Entity\\Product\\ProductOptionValue'), ($container->services['sylius.translation_locale_provider'] ?? self::getSylius_TranslationLocaleProviderService($container)));
    }
}
