<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Processor_PaymentRequest_HttpResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.processor.payment_request.http_response' shared service.
     *
     * @return \Sylius\Bundle\PaymentBundle\Processor\HttpResponseProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Processor/HttpResponseProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Processor/HttpResponseProcessor.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/HttpResponseProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/ServiceProviderAwareProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/AbstractServiceProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/GatewayFactoryHttpResponseProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/GatewayFactoryNameProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/GatewayFactoryNameProvider.php';

        return $container->privates['sylius.processor.payment_request.http_response'] = new \Sylius\Bundle\PaymentBundle\Processor\HttpResponseProcessor(($container->privates['sylius.announcer.payment_request'] ?? $container->load('getSylius_Announcer_PaymentRequestService')), new \Sylius\Bundle\PaymentBundle\Provider\GatewayFactoryHttpResponseProvider(($container->privates['sylius.provider.payment_request.gateway_factory_name'] ??= new \Sylius\Bundle\PaymentBundle\Provider\GatewayFactoryNameProvider()), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'offline' => ['privates', 'sylius.provider.payment_request.http_response.offline', 'getSylius_Provider_PaymentRequest_HttpResponse_OfflineService', true],
        ], [
            'offline' => 'Sylius\\Bundle\\PaymentBundle\\Provider\\ActionsHttpResponseProvider',
        ])));
    }
}
