<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Controller_Account_RequestPasswordResetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.controller.account.request_password_reset' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Action\Account\RequestPasswordResetAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Action/Account/RequestPasswordResetAction.php';

        return $container->services['sylius_admin.controller.account.request_password_reset'] = new \Sylius\Bundle\AdminBundle\Action\Account\RequestPasswordResetAction(($container->services['form.factory'] ?? self::getForm_FactoryService($container)), ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['twig'] ?? self::getTwigService($container)));
    }
}
