<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Validator_CatalogPromotionActionTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.validator.catalog_promotion_action_type' shared service.
     *
     * @return \Sylius\Bundle\PromotionBundle\Validator\CatalogPromotionActionTypeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Validator/CatalogPromotionActionTypeValidator.php';

        return $container->privates['sylius.validator.catalog_promotion_action_type'] = new \Sylius\Bundle\PromotionBundle\Validator\CatalogPromotionActionTypeValidator($container->parameters['sylius.catalog_promotion.actions_types']);
    }
}
