<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Twig_Component_ProductAttribute_FormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.twig.component.product_attribute.form' service.
     *
     * @return \Sylius\Bundle\AdminBundle\Twig\Component\ProductAttribute\FormComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentWithFormTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/LiveCollectionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/TemplatePropTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/LiveComponent/HookableLiveComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/ResourceFormComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/Component/ProductAttribute/FormComponent.php';

        $container->factories['sylius_admin.twig.component.product_attribute.form'] = function ($container) {
            $a = ($container->services['form.factory'] ?? self::getForm_FactoryService($container));

            if (isset($container->services['sylius_admin.twig.component.product_attribute.form'])) {
                return $container->services['sylius_admin.twig.component.product_attribute.form'];
            }

            return new \Sylius\Bundle\AdminBundle\Twig\Component\ProductAttribute\FormComponent(($container->services['sylius.repository.product_attribute'] ?? $container->load('getSylius_Repository_ProductAttributeService')), $a, 'App\\Entity\\Product\\ProductAttribute', 'Sylius\\Bundle\\AdminBundle\\Form\\Type\\ProductAttributeType');
        };

        return $container->factories['sylius_admin.twig.component.product_attribute.form']($container);
    }
}
