<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Repository_MollieGatewayConfigTranslationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.repository.mollie_gateway_config_translation' shared service.
     *
     * @return \Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius_mollie.repository.mollie_gateway_config_translation'])) {
            return $container->services['sylius_mollie.repository.mollie_gateway_config_translation'];
        }

        return $container->services['sylius_mollie.repository.mollie_gateway_config_translation'] = $a->getRepository('Sylius\\MolliePlugin\\Entity\\MollieGatewayConfigTranslation');
    }
}
