<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Form_Type_Translation_PaymentMethodTranslationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_mollie.form.type.translation.payment_method_translation' shared service.
     *
     * @return \Sylius\MolliePlugin\Form\Type\Translation\MollieGatewayConfigTranslationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Form/Type/Translation/MollieGatewayConfigTranslationType.php';

        return $container->privates['sylius_mollie.form.type.translation.payment_method_translation'] = new \Sylius\MolliePlugin\Form\Type\Translation\MollieGatewayConfigTranslationType('Sylius\\MolliePlugin\\Entity\\MollieGatewayConfigTranslation');
    }
}
