<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Product_Update_Content_Form_Sections_Taxonomy_Hookable_ProductTaxonsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product.update.content.form.sections.taxonomy.hookable.product_taxons' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product.update.content.form.sections.taxonomy.hookable.product_taxons'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_admin.product.update.content.form.sections.taxonomy', 'product_taxons', 'sylius_admin:product:form:product_taxons', ['form' => '@=_context.form', 'template' => '@SyliusAdmin/product/form/sections/taxonomy/product_taxons.html.twig'], [], ['auto_open' => false], 0, true);
    }
}
