<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Product_Show_Content_PageBody_General_ConfigurableProduct_Pricinghead_Hookable_DiscountedByService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product.show.content.page_body.general.configurable_product.pricing#head.hookable.discounted_by' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product.show.content.page_body.general.configurable_product.pricing#head.hookable.discounted_by'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.product.show.content.page_body.general.configurable_product.pricing#head', 'discounted_by', '@SyliusAdmin/product/show/content/page_body/general/shared/pricing/head/discounted_by.html.twig', [], [], 100, true);
    }
}
