<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusPaypal_Controller_UpdatePaypalOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_paypal.controller.update_paypal_order' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\UpdatePayPalOrderAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/UpdatePayPalOrderAction.php';

        return $container->services['sylius_paypal.controller.update_paypal_order'] = new \Sylius\PayPalPlugin\Controller\UpdatePayPalOrderAction(($container->privates['sylius_paypal.provider.payment'] ?? $container->load('getSyliusPaypal_Provider_PaymentService')), ($container->privates['sylius_paypal.api.cache_authorize_client'] ?? $container->load('getSyliusPaypal_Api_CacheAuthorizeClientService')), ($container->privates['sylius_paypal.api.update_order'] ?? $container->load('getSyliusPaypal_Api_UpdateOrderService')), ($container->services['sylius.factory.address'] ?? $container->load('getSylius_Factory_AddressService')), ($container->services['sylius.order_processing.order_processor'] ?? $container->load('getSylius_OrderProcessing_OrderProcessorService')));
    }
}
