<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Cart_Index_Content_Form_Sections_Generalright_Hookable_SummaryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.cart.index.content.form.sections.general#right.hookable.summary' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.cart.index.content.form.sections.general#right.hookable.summary'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_shop.cart.index.content.form.sections.general#right', 'summary', 'sylius_shop:cart:summary', ['cart' => '@=_context.cart', 'template' => '@SyliusShop/cart/index/content/form/sections/general/summary.html.twig'], [], [], 100, true);
    }
}
