<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusShop_Provider_OrderPay_PayResponse_PaymentRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_shop.provider.order_pay.pay_response.payment_request' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\OrderPay\Provider\PaymentRequestPayResponseProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/OrderPay/Provider/PayResponseProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/OrderPay/Provider/PaymentRequestPayResponseProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/OrderPay/Provider/UrlProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/OrderPay/Provider/UrlProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Payment/Factory/PaymentRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Payment/Factory/PaymentRequestFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/DefaultPayloadProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/DefaultPayloadProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/OrderPay/Resolver/PaymentToPayResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/OrderPay/Resolver/PaymentToPayResolver.php';

        return $container->privates['sylius_shop.provider.order_pay.pay_response.payment_request'] = new \Sylius\Bundle\CoreBundle\OrderPay\Provider\PaymentRequestPayResponseProvider(($container->services['sylius.factory.payment_request'] ??= new \Sylius\Component\Payment\Factory\PaymentRequestFactory('App\\Entity\\Payment\\PaymentRequest')), ($container->services['sylius.repository.payment_request'] ?? $container->load('getSylius_Repository_PaymentRequestService')), ($container->privates['sylius.provider.payment_request.default_action'] ?? self::getSylius_Provider_PaymentRequest_DefaultActionService($container)), ($container->privates['sylius.provider.payment_request.default_payload'] ??= new \Sylius\Bundle\PaymentBundle\Provider\DefaultPayloadProvider()), ($container->privates['sylius.checker.finalized_payment_request'] ?? $container->load('getSylius_Checker_FinalizedPaymentRequestService')), ($container->privates['sylius_shop.resolver.order_pay.payment_to_pay'] ??= new \Sylius\Bundle\CoreBundle\OrderPay\Resolver\PaymentToPayResolver('new')), new \Sylius\Bundle\CoreBundle\OrderPay\Provider\UrlProvider(($container->privates['sylius.processor.order_pay.route_parameters'] ?? $container->load('getSylius_Processor_OrderPay_RouteParametersService')), 'sylius_shop_payment_request_pay', $container->parameters['sylius_shop.order_pay.payment_request_pay_route_parameters']));
    }
}
