<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_AdminUserProvider_EmailOrNameBasedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.admin_user_provider.email_or_name_based' shared service.
     *
     * @return \Sylius\Bundle\UserBundle\Provider\UsernameOrEmailProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['sylius.admin_user_provider.email_or_name_based'] = $container->createProxy('UsernameOrEmailProviderGhost37f0eb1', static fn () => \UsernameOrEmailProviderGhost37f0eb1::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/Provider/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/Provider/UsernameOrEmailProvider.php';

        return ($lazyLoad->__construct('App\\Entity\\User\\AdminUser', ($container->services['sylius.repository.admin_user'] ?? $container->load('getSylius_Repository_AdminUserService')), ($container->privates['sylius.canonicalizer'] ??= new \Sylius\Component\User\Canonicalizer\Canonicalizer())) && false ?: $lazyLoad);
    }
}
