<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusFixtures_FixtureRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_fixtures.fixture_registry' shared service.
     *
     * @return \Sylius\Bundle\FixturesBundle\Fixture\FixtureRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/FixtureRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/FixtureRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/LocaleFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/CurrencyFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/GeographicalFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/AbstractResourceFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/PaymentMethodFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ShippingCategoryFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ShippingMethodFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/CatalogPromotionFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ChannelFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/CustomerGroupFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ShopUserFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/AdminUserFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ProductAssociationTypeFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ProductAssociationFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/SimilarProductAssociationFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ProductOptionFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ProductAttributeFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ProductReviewFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/TaxCategoryFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/TaxRateFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/PromotionFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/TaxonFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/ProductFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/AddressFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/PaymentFixture.php';

        $container->services['sylius_fixtures.fixture_registry'] = $instance = new \Sylius\Bundle\FixturesBundle\Fixture\FixtureRegistry();

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));
        $b = new \Sylius\Bundle\CoreBundle\Fixture\ProductAssociationTypeFixture($a, ($container->services['sylius.fixture.example_factory.product_association_type'] ?? $container->load('getSylius_Fixture_ExampleFactory_ProductAssociationTypeService')));
        $c = new \Sylius\Bundle\CoreBundle\Fixture\ProductAssociationFixture($a, ($container->services['sylius.fixture.example_factory.product_association'] ?? $container->load('getSylius_Fixture_ExampleFactory_ProductAssociationService')));

        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\LocaleFixture(($container->services['sylius.factory.locale'] ??= new \Sylius\Resource\Factory\Factory('App\\Entity\\Locale\\Locale')), $a, 'fr_FR'));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\CurrencyFixture(($container->services['sylius.factory.currency'] ??= new \Sylius\Resource\Factory\Factory('App\\Entity\\Currency\\Currency')), $a));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\GeographicalFixture(($container->services['sylius.factory.country'] ??= new \Sylius\Resource\Factory\Factory('App\\Entity\\Addressing\\Country')), $a, ($container->services['sylius.factory.province'] ??= new \Sylius\Resource\Factory\Factory('App\\Entity\\Addressing\\Province')), $a, ($container->services['sylius.factory.zone'] ?? $container->load('getSylius_Factory_ZoneService')), $a));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\PaymentMethodFixture($a, ($container->services['sylius.fixture.example_factory.payment_method'] ?? $container->load('getSylius_Fixture_ExampleFactory_PaymentMethodService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\ShippingCategoryFixture($a, ($container->services['sylius.fixture.example_factory.shipping_category'] ?? $container->load('getSylius_Fixture_ExampleFactory_ShippingCategoryService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\ShippingMethodFixture($a, ($container->services['sylius.fixture.example_factory.shipping_method'] ?? $container->load('getSylius_Fixture_ExampleFactory_ShippingMethodService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\CatalogPromotionFixture($a, ($container->services['sylius.fixture.example_factory.catalog_promotion'] ?? $container->load('getSylius_Fixture_ExampleFactory_CatalogPromotionService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\ChannelFixture($a, ($container->services['sylius.fixture.example_factory.channel'] ?? $container->load('getSylius_Fixture_ExampleFactory_ChannelService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\CustomerGroupFixture($a, ($container->services['sylius.fixture.example_factory.customer_group'] ?? $container->load('getSylius_Fixture_ExampleFactory_CustomerGroupService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\ShopUserFixture($a, ($container->services['sylius.fixture.example_factory.shop_user'] ?? $container->load('getSylius_Fixture_ExampleFactory_ShopUserService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\AdminUserFixture($a, ($container->services['sylius.fixture.example_factory.admin_user'] ?? $container->load('getSylius_Fixture_ExampleFactory_AdminUserService'))));
        $instance->addFixture($b);
        $instance->addFixture($c);
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\SimilarProductAssociationFixture($b, $c, ($container->services['sylius.repository.product'] ?? $container->load('getSylius_Repository_ProductService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\ProductOptionFixture($a, ($container->services['sylius.fixture.example_factory.product_option'] ?? $container->load('getSylius_Fixture_ExampleFactory_ProductOptionService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\ProductAttributeFixture($a, ($container->services['sylius.fixture.example_factory.product_attribute'] ?? $container->load('getSylius_Fixture_ExampleFactory_ProductAttributeService')), $container->parameters['sylius.attribute.attribute_types']));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\ProductReviewFixture($a, ($container->services['sylius.fixture.example_factory.product_review'] ?? $container->load('getSylius_Fixture_ExampleFactory_ProductReviewService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\TaxCategoryFixture($a, ($container->services['sylius.fixture.example_factory.tax_category'] ?? $container->load('getSylius_Fixture_ExampleFactory_TaxCategoryService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\TaxRateFixture($a, ($container->services['sylius.fixture.example_factory.tax_rate'] ?? $container->load('getSylius_Fixture_ExampleFactory_TaxRateService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\PromotionFixture($a, ($container->services['sylius.fixture.example_factory.promotion'] ?? $container->load('getSylius_Fixture_ExampleFactory_PromotionService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\TaxonFixture($a, ($container->services['sylius.fixture.example_factory.taxon'] ?? $container->load('getSylius_Fixture_ExampleFactory_TaxonService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\ProductFixture($a, ($container->services['sylius.fixture.example_factory.product'] ?? $container->load('getSylius_Fixture_ExampleFactory_ProductService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\OrderFixture($a, ($container->services['sylius.fixture.example_factory.order'] ?? $container->load('getSylius_Fixture_ExampleFactory_OrderService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\AddressFixture($a, ($container->services['sylius.fixture.example_factory.address'] ?? $container->load('getSylius_Fixture_ExampleFactory_AddressService'))));
        $instance->addFixture(new \Sylius\Bundle\CoreBundle\Fixture\PaymentFixture(($container->services['sylius.repository.payment'] ?? $container->load('getSylius_Repository_PaymentService')), ($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container)), $a));

        return $instance;
    }
}
