<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Listener_ResourceDeleteExceptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.listener.resource_delete_exception' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\EventListener\ResourceDeleteExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/EventListener/ResourceDeleteExceptionListener.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['sylius_admin.listener.resource_delete_exception'])) {
            return $container->services['sylius_admin.listener.resource_delete_exception'];
        }

        return $container->services['sylius_admin.listener.resource_delete_exception'] = new \Sylius\Bundle\AdminBundle\EventListener\ResourceDeleteExceptionListener($a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
