<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Shared_Order_Show_Summary_Addresses_Billing_Body_Hookable_AddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.shared.order.show.summary.addresses.billing.body.hookable.address' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.shared.order.show.summary.addresses.billing.body.hookable.address'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_shop.shared.order.show.summary.addresses.billing.body', 'address', '@SyliusShop/shared/address.html.twig', [], [], 0, true);
    }
}
