<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Validator_ValidTextAttributeConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.validator.valid_text_attribute_configuration' shared service.
     *
     * @return \Sylius\Bundle\AttributeBundle\Validator\Constraints\ValidTextAttributeConfigurationValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AttributeBundle/Validator/Constraints/ValidTextAttributeConfigurationValidator.php';

        return $container->privates['sylius.validator.valid_text_attribute_configuration'] = new \Sylius\Bundle\AttributeBundle\Validator\Constraints\ValidTextAttributeConfigurationValidator();
    }
}
