<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_Workflow_Shipment_ResolveOrderShipmentStateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.listener.workflow.shipment.resolve_order_shipment_state' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\Workflow\Shipment\ResolveOrderShipmentStateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/Workflow/Shipment/ResolveOrderShipmentStateListener.php';

        return $container->privates['sylius.listener.workflow.shipment.resolve_order_shipment_state'] = new \Sylius\Bundle\CoreBundle\EventListener\Workflow\Shipment\ResolveOrderShipmentStateListener(($container->services['sylius.state_resolver.order_shipping'] ?? $container->load('getSylius_StateResolver_OrderShippingService')));
    }
}
