<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_ResourceController_RedirectHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_admin.resource_controller.redirect_handler' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Controller\RedirectHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Controller/RedirectHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Controller/RedirectHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Controller/RedirectHandler.php';

        return $container->privates['sylius_admin.resource_controller.redirect_handler'] = new \Sylius\Bundle\AdminBundle\Controller\RedirectHandler(new \Sylius\Bundle\ResourceBundle\Controller\RedirectHandler(($container->services['router'] ?? self::getRouterService($container))), ($container->services['sylius.grid.filter_storage'] ?? self::getSylius_Grid_FilterStorageService($container)));
    }
}
