<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Assigner_OrderToken_UniqueIdBasedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.assigner.order_token.unique_id_based' shared service.
     *
     * @return \Sylius\Component\Core\TokenAssigner\UniqueIdBasedOrderTokenAssigner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/TokenAssigner/OrderTokenAssignerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/TokenAssigner/UniqueIdBasedOrderTokenAssigner.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Generator/RandomnessGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Generator/RandomnessGenerator.php';

        return $container->services['sylius.assigner.order_token.unique_id_based'] = new \Sylius\Component\Core\TokenAssigner\UniqueIdBasedOrderTokenAssigner(($container->services['sylius.random_generator'] ??= new \Sylius\Resource\Generator\RandomnessGenerator()), 64);
    }
}
