<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Account_Dashboard_Index_Content_Main_Section_UserInfo_Hookable_UserDetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.account.dashboard.index.content.main.section.user_info.hookable.user_details' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.account.dashboard.index.content.main.section.user_info.hookable.user_details'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_shop.account.dashboard.index.content.main.section.user_info', 'user_details', '@SyliusShop/account/dashboard/index/content/main/section/user_info/details.html.twig', [], [], 0, true);
    }
}
