<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_CommandDispatcher_PriceHistory_BatchedApplyLowestPriceOnChannelPricingsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.command_dispatcher.price_history.batched_apply_lowest_price_on_channel_pricings' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\PriceHistory\CommandDispatcher\BatchedApplyLowestPriceOnChannelPricingsCommandDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/PriceHistory/CommandDispatcher/ApplyLowestPriceOnChannelPricingsCommandDispatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/PriceHistory/CommandDispatcher/BatchedApplyLowestPriceOnChannelPricingsCommandDispatcher.php';

        return $container->privates['sylius.command_dispatcher.price_history.batched_apply_lowest_price_on_channel_pricings'] = new \Sylius\Bundle\CoreBundle\PriceHistory\CommandDispatcher\BatchedApplyLowestPriceOnChannelPricingsCommandDispatcher(($container->services['sylius.repository.channel_pricing'] ?? $container->load('getSylius_Repository_ChannelPricingService')), ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)), 100);
    }
}
