<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Form_Type_PaymentSurchargeTypeChoiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_mollie.form.type.payment_surcharge_type_choice' shared service.
     *
     * @return \Sylius\MolliePlugin\Form\Type\PaymentSurchargeFeeTypeChoiceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Form/Type/PaymentSurchargeFeeTypeChoiceType.php';

        return $container->privates['sylius_mollie.form.type.payment_surcharge_type_choice'] = new \Sylius\MolliePlugin\Form\Type\PaymentSurchargeFeeTypeChoiceType();
    }
}
