<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Factory_PaymentDetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.factory.payment_details' shared service.
     *
     * @return \Sylius\MolliePlugin\Factory\PaymentDetailsFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Factory/PaymentDetailsFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Factory/PaymentDetailsFactory.php';

        return $container->services['sylius_mollie.factory.payment_details'] = new \Sylius\MolliePlugin\Factory\PaymentDetailsFactory();
    }
}
