<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_StateMachine_Applicator_SubscriptionAndSyliusPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.state_machine.applicator.subscription_and_sylius_payment' shared service.
     *
     * @return \Sylius\MolliePlugin\StateMachine\Applicator\SubscriptionAndSyliusPaymentApplicator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/StateMachine/Applicator/SubscriptionAndSyliusPaymentApplicatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/StateMachine/Applicator/SubscriptionAndSyliusPaymentApplicator.php';

        return $container->services['sylius_mollie.state_machine.applicator.subscription_and_sylius_payment'] = new \Sylius\MolliePlugin\StateMachine\Applicator\SubscriptionAndSyliusPaymentApplicator(($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container)));
    }
}
