<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Product_Create_Content_Form_Sections_Attributes_List_Translations_Field_Hookable_LanguageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product.create.content.form.sections.attributes.list.translations.field.hookable.language' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product.create.content.form.sections.attributes.list.translations.field.hookable.language'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.product.create.content.form.sections.attributes.list.translations.field', 'language', '@SyliusAdmin/product/form/sections/attributes/list/translations/field/language.html.twig', [], [], 200, true);
    }
}
