<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Order_ThankYou_Content_Buttonsguest_Hookable_ChangePaymentMethodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.order.thank_you.content.buttons#guest.hookable.change_payment_method' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.order.thank_you.content.buttons#guest.hookable.change_payment_method'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_shop.order.thank_you.content.buttons#guest', 'change_payment_method', '@SyliusPayPalPlugin/shop/order/thank_you/content/buttons/change_payment_method.html.twig', [], [], 100, true);
    }
}
