<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Calculator_PaymentFee_FixedAmountAndPercentageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_mollie.calculator.payment_fee.fixed_amount_and_percentage' shared service.
     *
     * @return \Sylius\MolliePlugin\Calculator\PaymentFee\FixedAmountAndPercentageCalculator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Calculator/PaymentFee/PaymentSurchargeCalculatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Calculator/PaymentFee/FixedAmountAndPercentageCalculator.php';

        return $container->privates['sylius_mollie.calculator.payment_fee.fixed_amount_and_percentage'] = new \Sylius\MolliePlugin\Calculator\PaymentFee\FixedAmountAndPercentageCalculator(($container->services['sylius.factory.adjustment'] ?? $container->load('getSylius_Factory_AdjustmentService')), ($container->privates['sylius_mollie.calculator.payment_fee.percentage'] ?? $container->load('getSyliusMollie_Calculator_PaymentFee_PercentageService')), ($container->privates['sylius_mollie.calculator.payment_fee.fixed_amount'] ?? $container->load('getSyliusMollie_Calculator_PaymentFee_FixedAmountService')), ($container->services['sylius_mollie.provider.divisor'] ??= new \Sylius\MolliePlugin\Provider\DivisorProvider()));
    }
}
