<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Twig_ErrorTemplateFinderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_admin.twig.error_template_finder' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Twig\ErrorTemplateFinder\ErrorTemplateFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/ErrorTemplateFinder/ErrorTemplateFinderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/ErrorTemplateFinder/ErrorTemplateFinder.php';

        return $container->privates['sylius_admin.twig.error_template_finder'] = new \Sylius\Bundle\AdminBundle\Twig\ErrorTemplateFinder\ErrorTemplateFinder(($container->privates['sylius.section_resolver.uri_based'] ?? self::getSylius_SectionResolver_UriBasedService($container)), ($container->privates['sylius_admin.provider.logged_in_admin_user'] ?? $container->load('getSyliusAdmin_Provider_LoggedInAdminUserService')), ($container->services['twig'] ?? self::getTwigService($container)));
    }
}
