<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Controller_Admin_OnboardingWizard_StatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.controller.admin.onboarding_wizard.status' shared service.
     *
     * @return \Sylius\MolliePlugin\Controller\Admin\OnboardingWizard\StatusAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Controller/Admin/OnboardingWizard/StatusAction.php';

        return $container->services['sylius_mollie.controller.admin.onboarding_wizard.status'] = new \Sylius\MolliePlugin\Controller\Admin\OnboardingWizard\StatusAction(($container->services['sylius_mollie.context.admin_user'] ?? $container->load('getSyliusMollie_Context_AdminUserService')));
    }
}
