<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Security_PasswordUpdaterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.security.password_updater' shared service.
     *
     * @return \Sylius\Component\User\Security\PasswordUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/User/Security/PasswordUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/User/Security/PasswordUpdater.php';

        return $container->privates['sylius.security.password_updater'] = new \Sylius\Component\User\Security\PasswordUpdater(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
