<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Validator_GroupsGenerator_ShippingMethodConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.validator.groups_generator.shipping_method_configuration' shared service.
     *
     * @return \Sylius\Bundle\ShippingBundle\Validator\GroupsGenerator\ShippingMethodConfigurationGroupsGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShippingBundle/Validator/GroupsGenerator/ShippingMethodConfigurationGroupsGenerator.php';

        return $container->privates['sylius_api.validator.groups_generator.shipping_method_configuration'] = new \Sylius\Bundle\ShippingBundle\Validator\GroupsGenerator\ShippingMethodConfigurationGroupsGenerator($container->parameters['sylius.shipping.shipping_method_calculator.validation_groups']);
    }
}
