<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Checker_PromotionEligibilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.checker.promotion_eligibility' shared service.
     *
     * @return \Sylius\Component\Promotion\Checker\Eligibility\CompositePromotionEligibilityChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionEligibilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Checker/Eligibility/CompositePromotionEligibilityChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionDurationEligibilityChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionUsageLimitEligibilityChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionSubjectCouponEligibilityChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionRulesEligibilityChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionArchivalEligibilityChecker.php';

        $a = ($container->privates['sylius.registry.promotion.rule_checker'] ?? $container->load('getSylius_Registry_Promotion_RuleCheckerService'));

        if (isset($container->privates['sylius.checker.promotion_eligibility'])) {
            return $container->privates['sylius.checker.promotion_eligibility'];
        }

        return $container->privates['sylius.checker.promotion_eligibility'] = new \Sylius\Component\Promotion\Checker\Eligibility\CompositePromotionEligibilityChecker([new \Sylius\Component\Promotion\Checker\Eligibility\PromotionDurationEligibilityChecker(), new \Sylius\Component\Promotion\Checker\Eligibility\PromotionUsageLimitEligibilityChecker(), new \Sylius\Component\Promotion\Checker\Eligibility\PromotionSubjectCouponEligibilityChecker(($container->privates['sylius.checker.promotion_coupon_eligibility'] ?? $container->load('getSylius_Checker_PromotionCouponEligibilityService'))), new \Sylius\Component\Promotion\Checker\Eligibility\PromotionRulesEligibilityChecker($a), new \Sylius\Component\Promotion\Checker\Eligibility\PromotionArchivalEligibilityChecker()]);
    }
}
