<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Product_Update_Content_Form_Sections_ChannelPricing_Hookable_PriceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product.update.content.form.sections.channel_pricing.hookable.price' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\DisabledHookable
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/DisabledHookable.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product.update.content.form.sections.channel_pricing.hookable.price'] = new \Sylius\TwigHooks\Hookable\DisabledHookable('sylius_admin.product.update.content.form.sections.channel_pricing', 'price', [], [], NULL);
    }
}
