<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusShop_Form_Type_CartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_shop.form.type.cart' shared service.
     *
     * @return \Sylius\Bundle\ShopBundle\Form\Type\CartType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Form/Type/CartType.php';

        return $container->privates['sylius_shop.form.type.cart'] = new \Sylius\Bundle\ShopBundle\Form\Type\CartType();
    }
}
