<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Payum_Action_CaptureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.payum.action.capture' shared service.
     *
     * @return \Sylius\MolliePlugin\Payum\Action\CaptureAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Action/ActionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/ApiAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Payum/Action/BaseApiAwareAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Security/GenericTokenFactoryAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/GatewayAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/GatewayAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Payum/Action/CaptureAction.php';

        return $container->services['sylius_mollie.payum.action.capture'] = new \Sylius\MolliePlugin\Payum\Action\CaptureAction(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['sylius_mollie.resolver.mollie_api_client_key'] ?? $container->load('getSyliusMollie_Resolver_MollieApiClientKeyService')), ($container->services['sylius.repository.payment'] ?? $container->load('getSylius_Repository_PaymentService')));
    }
}
