<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Controller_Shop_PaymentFeeCalculateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.controller.shop.payment_fee_calculate' shared service.
     *
     * @return \Sylius\MolliePlugin\Controller\Shop\PaymentFeeCalculateAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Controller/Shop/PaymentFeeCalculateAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Calculator/Clearer/PaymentFeeAdjustmentClearerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Calculator/Clearer/PaymentFeeAdjustmentClearer.php';

        return $container->services['sylius_mollie.controller.shop.payment_fee_calculate'] = new \Sylius\MolliePlugin\Controller\Shop\PaymentFeeCalculateAction(($container->privates['sylius_mollie.calculator.payment_fee.composite'] ?? $container->load('getSyliusMollie_Calculator_PaymentFee_CompositeService')), ($container->services['sylius.context.cart'] ?? self::getSylius_Context_CartService($container)), ($container->services['sylius_mollie.repository.mollie_gateway_config'] ?? self::getSyliusMollie_Repository_MollieGatewayConfigService($container)), ($container->privates['sylius.aggregator.adjustments_by_label'] ??= new \Sylius\Component\Order\Aggregator\AdjustmentsByLabelAggregator()), ($container->services['sylius_mollie.converter.price_to_amount'] ?? $container->load('getSyliusMollie_Converter_PriceToAmountService')), ($container->services['twig'] ?? self::getTwigService($container)), ($container->privates['sylius_mollie.calculator.clearer.payment_fee_adjustment'] ??= new \Sylius\MolliePlugin\Calculator\Clearer\PaymentFeeAdjustmentClearer()));
    }
}
