<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Validator_CheckoutCompletionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.validator.checkout_completion' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Validator\Constraints\CheckoutCompletionValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Validator/Constraints/CheckoutCompletionValidator.php';

        $a = ($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container));

        if (isset($container->privates['sylius_api.validator.checkout_completion'])) {
            return $container->privates['sylius_api.validator.checkout_completion'];
        }

        return $container->privates['sylius_api.validator.checkout_completion'] = new \Sylius\Bundle\ApiBundle\Validator\Constraints\CheckoutCompletionValidator(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), $a);
    }
}
