<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Twig_Context_Factory_DefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.twig.context.factory.default' shared service.
     *
     * @return \Sylius\Resource\Twig\Context\Factory\DefaultContextFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Twig/Context/Factory/ContextFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Twig/Context/Factory/DefaultContextFactory.php';

        return $container->privates['sylius.twig.context.factory.default'] = new \Sylius\Resource\Twig\Context\Factory\DefaultContextFactory();
    }
}
