<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_AdminUser_Update_Content_Form_Sections_Hookable_GeneralService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.admin_user.update.content.form.sections.hookable.general' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\DisabledHookable
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/DisabledHookable.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.admin_user.update.content.form.sections.hookable.general'] = new \Sylius\TwigHooks\Hookable\DisabledHookable('sylius_admin.admin_user.update.content.form.sections', 'general', [], [], NULL);
    }
}
