<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Form_Type_CatalogPromotionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_admin.form.type.catalog_promotion' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Form\Type\CatalogPromotionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Form/Type/CatalogPromotionType.php';

        return $container->privates['sylius_admin.form.type.catalog_promotion'] = new \Sylius\Bundle\AdminBundle\Form\Type\CatalogPromotionType($container->parameters['sylius.catalog_promotion.scopes_types'], $container->parameters['sylius.catalog_promotion.actions_types']);
    }
}
