<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_PaymentRequest_CommandBus_Middleware_HandleMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.payment_request.command_bus.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $container->privates['sylius.payment_request.command_bus.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Symfony\\Component\\Process\\Messenger\\RunProcessMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.lvaixHp'] ?? $container->load('get_Messenger_HandlerDescriptor_LvaixHpService'));
        }, 1), 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.1NINQ86'] ?? $container->load('get_Messenger_HandlerDescriptor_1NINQ86Service'));
        }, 1), 'Symfony\\Component\\HttpClient\\Messenger\\PingWebhookMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.rcsydd6'] ?? $container->load('get_Messenger_HandlerDescriptor_Rcsydd6Service'));
        }, 1), 'Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.40g2gPq'] ?? $container->load('get_Messenger_HandlerDescriptor_40g2gPqService'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.HS7CLjf'] ?? $container->load('get_Messenger_HandlerDescriptor_HS7CLjfService'));
        }, 1), 'Sylius\\Bundle\\PaymentBundle\\Command\\Offline\\CapturePaymentRequest' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.ZWQe76K'] ?? $container->load('get_Messenger_HandlerDescriptor_ZWQe76KService'));
        }, 1), 'Sylius\\Bundle\\PaymentBundle\\Command\\Offline\\StatusPaymentRequest' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.4cmZJgS'] ?? $container->load('get_Messenger_HandlerDescriptor_4cmZJgSService'));
        }, 1), 'Sylius\\Bundle\\PayumBundle\\PaymentRequest\\Command\\CapturePaymentRequest' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.fH6rCQI'] ?? $container->load('get_Messenger_HandlerDescriptor_FH6rCQIService'));
        }, 1), 'Sylius\\Bundle\\PayumBundle\\PaymentRequest\\Command\\AuthorizePaymentRequest' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.9ODZ3qe'] ?? $container->load('get_Messenger_HandlerDescriptor_9ODZ3qeService'));
        }, 1), 'Sylius\\Bundle\\PayumBundle\\PaymentRequest\\Command\\StatusPaymentRequest' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.fCTJok.'] ?? $container->load('get_Messenger_HandlerDescriptor_FCTJok_Service'));
        }, 1), 'Sylius\\Bundle\\PayumBundle\\PaymentRequest\\Command\\NotifyPaymentRequest' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.a2jMKZC'] ?? $container->load('get_Messenger_HandlerDescriptor_A2jMKZCService'));
        }, 1)]), false);

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
