<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusPaypal_Api_UpdateOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_paypal.api.update_order' shared service.
     *
     * @return \Sylius\PayPalPlugin\Api\UpdateOrderApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/UpdateOrderApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Api/UpdateOrderApi.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PaymentReferenceNumberProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Provider/PaymentReferenceNumberProvider.php';

        return $container->privates['sylius_paypal.api.update_order'] = new \Sylius\PayPalPlugin\Api\UpdateOrderApi(($container->privates['sylius_paypal.client.paypal'] ?? $container->load('getSyliusPaypal_Client_PaypalService')), ($container->privates['sylius_paypal.provider.payment_reference_number'] ??= new \Sylius\PayPalPlugin\Provider\PaymentReferenceNumberProvider()), ($container->privates['sylius_paypal.provider.paypal_item_data'] ?? $container->load('getSyliusPaypal_Provider_PaypalItemDataService')));
    }
}
