<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_PromotionRuleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.form.type.promotion_rule' shared service.
     *
     * @return \Sylius\Bundle\PromotionBundle\Form\Type\PromotionRuleType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Form/Type/AbstractConfigurablePromotionElementType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionRuleType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Registry/FormTypeRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Registry/FormTypeRegistry.php';

        $a = new \Sylius\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry();
        $a->add('customer_group', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\CustomerGroupConfigurationType');
        $a->add('nth_order', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\NthOrderConfigurationType');
        $a->add('shipping_country', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ShippingCountryConfigurationType');
        $a->add('has_taxon', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\HasTaxonConfigurationType');
        $a->add('total_of_items_from_taxon', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ChannelBasedTotalOfItemsFromTaxonConfigurationType');
        $a->add('contains_product', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ContainsProductConfigurationType');
        $a->add('item_total', 'default', 'Sylius\\Bundle\\CoreBundle\\Form\\Type\\Promotion\\Rule\\ChannelBasedItemTotalConfigurationType');
        $a->add('cart_quantity', 'default', 'Sylius\\Bundle\\PromotionBundle\\Form\\Type\\Rule\\CartQuantityConfigurationType');

        return $container->privates['sylius.form.type.promotion_rule'] = new \Sylius\Bundle\PromotionBundle\Form\Type\PromotionRuleType('App\\Entity\\Promotion\\PromotionRule', $container->parameters['sylius.form.type.promotion_scope.validation_groups'], $a);
    }
}
