<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Customer_Show_Content_Sections_Hookable_OrderStatisticsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.customer.show.content.sections.hookable.order_statistics' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.customer.show.content.sections.hookable.order_statistics'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_admin.customer.show.content.sections', 'order_statistics', 'sylius_admin:customer:order_statistics', ['customerId' => '@=_context.resource.getId()', 'template' => '@SyliusAdmin/customer/show/component/order_statistics.html.twig'], [], [], 100, true);
    }
}
