<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Twig_Component_Order_AddressHistoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_admin.twig.component.order.address_history' service.
     *
     * @return \Sylius\Bundle\AdminBundle\Twig\Component\Order\AddressHistoryComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Twig/Component/HookableComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/Component/Order/AddressHistoryComponent.php';

        $container->factories['service_container']['sylius_admin.twig.component.order.address_history'] = function ($container) {
            return new \Sylius\Bundle\AdminBundle\Twig\Component\Order\AddressHistoryComponent(($container->services['sylius.repository.address_log_entry'] ?? $container->load('getSylius_Repository_AddressLogEntryService')));
        };

        return $container->factories['service_container']['sylius_admin.twig.component.order.address_history']($container);
    }
}
