<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Routing_Factory_OperationRoutePathFactory_DeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.routing.factory.operation_route_path_factory.delete' shared service.
     *
     * @return \Sylius\Resource\Symfony\Routing\Factory\RoutePath\DeleteOperationRoutePathFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Routing/Factory/RoutePath/OperationRoutePathFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Symfony/Routing/Factory/RoutePath/DeleteOperationRoutePathFactory.php';

        return $container->services['sylius.routing.factory.operation_route_path_factory.delete'] = new \Sylius\Resource\Symfony\Routing\Factory\RoutePath\DeleteOperationRoutePathFactory(($container->services['sylius.routing.factory.operation_route_path_factory.show'] ?? $container->load('getSylius_Routing_Factory_OperationRoutePathFactory_ShowService')));
    }
}
