<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Product_Show_Content_PageBody_General_Hookable_SimpleProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product.show.content.page_body.general.hookable.simple_product' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product.show.content.page_body.general.hookable.simple_product'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.product.show.content.page_body.general', 'simple_product', '@SyliusAdmin/product/show/content/page_body/general/simple_product.html.twig', [], [], 100, true);
    }
}
