<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Client_MollieApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.client.mollie_api' shared service.
     *
     * @return \Sylius\MolliePlugin\Client\MollieApiClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/mollie/mollie-api-php/src/MollieApiClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Client/MollieApiClient.php';

        return $container->services['sylius_mollie.client.mollie_api'] = new \Sylius\MolliePlugin\Client\MollieApiClient();
    }
}
