<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Resolver_MollieAllowedMethodsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.resolver.mollie_allowed_methods' shared service.
     *
     * @return \Sylius\MolliePlugin\Resolver\MollieAllowedMethodsResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Resolver/MollieAllowedMethodsResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Resolver/MollieAllowedMethodsResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Resolver/PaymentLocaleResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Resolver/PaymentLocaleResolver.php';

        $a = ($container->services['sylius_mollie.resolver.mollie_api_client_key'] ?? $container->load('getSyliusMollie_Resolver_MollieApiClientKeyService'));

        if (isset($container->services['sylius_mollie.resolver.mollie_allowed_methods'])) {
            return $container->services['sylius_mollie.resolver.mollie_allowed_methods'];
        }

        return $container->services['sylius_mollie.resolver.mollie_allowed_methods'] = new \Sylius\MolliePlugin\Resolver\MollieAllowedMethodsResolver($a, ($container->services['sylius_mollie.resolver.payment_locale'] ??= new \Sylius\MolliePlugin\Resolver\PaymentLocaleResolver()), ($container->services['sylius_mollie.converter.int_to_string'] ?? $container->load('getSyliusMollie_Converter_IntToStringService')));
    }
}
