<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_ProductTaxon_Index_Content_Header_TitleBlock_Hookable_TitleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product_taxon.index.content.header.title_block.hookable.title' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product_taxon.index.content.header.title_block.hookable.title'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_admin.product_taxon.index.content.header.title_block', 'title', 'sylius_admin:render_entity_with_template', ['entity' => 'App\\Entity\\Taxonomy\\Taxon', 'identifier' => '@=_context.resources.getRequestConfiguration().getRequest().attributes.get("taxonId")', 'template' => '@SyliusAdmin/product_taxon/index/content/header/title_block/title.html.twig'], [], [], 0, true);
    }
}
