<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_Checkout_ChangePaymentMethodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.form.type.checkout.change_payment_method' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Form\Type\Checkout\ChangePaymentMethodType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/ChangePaymentMethodType.php';

        return $container->privates['sylius.form.type.checkout.change_payment_method'] = new \Sylius\Bundle\CoreBundle\Form\Type\Checkout\ChangePaymentMethodType($container->parameters['sylius_core.checkout.payment.allowed_states']);
    }
}
