<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Validator_ShippingMethodRuleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.validator.shipping_method_rule' shared service.
     *
     * @return \Sylius\Bundle\ShippingBundle\Validator\ShippingMethodRuleValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShippingBundle/Validator/ShippingMethodRuleValidator.php';

        return $container->privates['sylius.validator.shipping_method_rule'] = new \Sylius\Bundle\ShippingBundle\Validator\ShippingMethodRuleValidator($container->parameters['sylius.shipping_method_rules'], $container->parameters['sylius.shipping.shipping_method_rule.validation_groups']);
    }
}
