<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Shared_Product_Card_Prices_Hookable_CatalogPromotionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.shared.product.card.prices.hookable.catalog_promotions' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.shared.product.card.prices.hookable.catalog_promotions'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_shop.shared.product.card.prices', 'catalog_promotions', 'sylius_shop:catalog_promotions', ['variant' => '@=_context.variant', 'applied_promotions' => '@=_context.applied_promotions', 'withDescription' => false], [], [], 100, true);
    }
}
