<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Twig_Component_EmailTemplate_FormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.twig.component.email_template.form' service.
     *
     * @return \Sylius\Bundle\UiBundle\Twig\Component\ResourceFormComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentWithFormTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/LiveCollectionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/TemplatePropTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/LiveComponent/HookableLiveComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/ResourceFormComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/ResourceFormComponent.php';

        $container->factories['sylius_mollie.twig.component.email_template.form'] = function ($container) {
            $a = ($container->services['form.factory'] ?? self::getForm_FactoryService($container));

            if (isset($container->services['sylius_mollie.twig.component.email_template.form'])) {
                return $container->services['sylius_mollie.twig.component.email_template.form'];
            }

            return new \Sylius\Bundle\UiBundle\Twig\Component\ResourceFormComponent(($container->services['sylius_mollie.repository.template_mollie_email'] ?? $container->load('getSyliusMollie_Repository_TemplateMollieEmailService')), $a, 'Sylius\\MolliePlugin\\Entity\\TemplateMollieEmail', 'Sylius\\MolliePlugin\\Form\\Type\\TemplateMollieEmailType');
        };

        return $container->factories['sylius_mollie.twig.component.email_template.form']($container);
    }
}
