<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Controller_PaymentRequestNotifyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.controller.payment_request_notify' shared service.
     *
     * @return \Sylius\Bundle\PaymentBundle\Action\PaymentRequestNotifyAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Action/PaymentRequestNotifyAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/NotifyResponseProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/NotifyResponseProvider.php';

        return $container->services['sylius.controller.payment_request_notify'] = new \Sylius\Bundle\PaymentBundle\Action\PaymentRequestNotifyAction(($container->services['sylius.repository.payment_request'] ?? $container->load('getSylius_Repository_PaymentRequestService')), ($container->privates['sylius.checker.finalized_payment_request'] ?? $container->load('getSylius_Checker_FinalizedPaymentRequestService')), ($container->privates['sylius.processor.payment_request.notify_payload'] ?? $container->load('getSylius_Processor_PaymentRequest_NotifyPayloadService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sylius.announcer.payment_request'] ?? $container->load('getSylius_Announcer_PaymentRequestService')), ($container->privates['sylius.provider.payment_request.notify_response'] ??= new \Sylius\Bundle\PaymentBundle\Provider\NotifyResponseProvider()));
    }
}
