<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Updater_ProductReview_AverageRatingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.updater.product_review.average_rating' shared service.
     *
     * @return \Sylius\Bundle\ReviewBundle\Updater\AverageRatingUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ReviewBundle/Updater/ReviewableRatingUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ReviewBundle/Updater/AverageRatingUpdater.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Review/Calculator/ReviewableRatingCalculatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Review/Calculator/AverageRatingCalculator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius.updater.product_review.average_rating'])) {
            return $container->services['sylius.updater.product_review.average_rating'];
        }

        return $container->services['sylius.updater.product_review.average_rating'] = new \Sylius\Bundle\ReviewBundle\Updater\AverageRatingUpdater(new \Sylius\Component\Review\Calculator\AverageRatingCalculator(), $a);
    }
}
