<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_ProductAttribute_Update_Content_Form_Configuration_Select_Hookable_MultipleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product_attribute.update.content.form.configuration.select.hookable.multiple' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product_attribute.update.content.form.configuration.select.hookable.multiple'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.product_attribute.update.content.form.configuration.select', 'multiple', '@SyliusAdmin/product_attribute/form/configuration/select/multiple.html.twig', [], [], 100, true);
    }
}
