<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Controller_PaymentMethodNotifyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.controller.payment_method_notify' shared service.
     *
     * @return \Sylius\Bundle\PaymentBundle\Action\PaymentMethodNotifyAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Action/PaymentMethodNotifyAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/NotifyPaymentProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/CompositeNotifyPaymentProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Payment/Factory/PaymentRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Payment/Factory/PaymentRequestFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/NotifyResponseProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PaymentBundle/Provider/NotifyResponseProvider.php';

        return $container->services['sylius.controller.payment_method_notify'] = new \Sylius\Bundle\PaymentBundle\Action\PaymentMethodNotifyAction(($container->services['sylius.repository.payment_method'] ?? self::getSylius_Repository_PaymentMethodService($container)), new \Sylius\Bundle\PaymentBundle\Provider\CompositeNotifyPaymentProvider(new RewindableGenerator(fn () => new \EmptyIterator(), 0)), ($container->services['sylius.factory.payment_request'] ??= new \Sylius\Component\Payment\Factory\PaymentRequestFactory('App\\Entity\\Payment\\PaymentRequest')), ($container->privates['sylius.processor.payment_request.notify_payload'] ?? $container->load('getSylius_Processor_PaymentRequest_NotifyPayloadService')), ($container->services['sylius.repository.payment_request'] ?? $container->load('getSylius_Repository_PaymentRequestService')), ($container->privates['sylius.announcer.payment_request'] ?? $container->load('getSylius_Announcer_PaymentRequestService')), ($container->privates['sylius.provider.payment_request.notify_response'] ??= new \Sylius\Bundle\PaymentBundle\Provider\NotifyResponseProvider()));
    }
}
