<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Account_Register_Content_Hookable_FormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.account.register.content.hookable.form' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.account.register.content.hookable.form'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_shop.account.register.content', 'form', 'sylius_shop:account:register:form', ['resource' => '@=_context.customer', 'form' => '@=_context.form', 'template' => '@SyliusShop/account/register/content/form.html.twig'], [], [], 0, true);
    }
}
