<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_ApplePay_Resolver_ApplePayDirectApiOrderPaymentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.apple_pay.resolver.apple_pay_direct_api_order_payment' shared service.
     *
     * @return \Sylius\MolliePlugin\ApplePay\Resolver\ApplePayDirectApiOrderPaymentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/ApplePay/Resolver/ApplePayDirectApiOrderPaymentResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/ApplePay/Resolver/ApplePayDirectApiOrderPaymentResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/mollie/mollie-api-php/src/MollieApiClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Client/MollieApiClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Resolver/PaymentLocaleResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Resolver/PaymentLocaleResolver.php';

        return $container->services['sylius_mollie.apple_pay.resolver.apple_pay_direct_api_order_payment'] = new \Sylius\MolliePlugin\ApplePay\Resolver\ApplePayDirectApiOrderPaymentResolver(($container->services['sylius_mollie.client.mollie_api'] ??= new \Sylius\MolliePlugin\Client\MollieApiClient()), ($container->services['sylius_mollie.resolver.mollie_api_client_key'] ?? $container->load('getSyliusMollie_Resolver_MollieApiClientKeyService')), ($container->services['sylius_mollie.converter.order'] ?? $container->load('getSyliusMollie_Converter_OrderService')), ($container->services['sylius_mollie.apple_pay.provider.order_payment_apple_pay_direct'] ?? $container->load('getSyliusMollie_ApplePay_Provider_OrderPaymentApplePayDirectService')), ($container->services['sylius_mollie.resolver.payment_locale'] ??= new \Sylius\MolliePlugin\Resolver\PaymentLocaleResolver()), ($container->services['sylius_mollie.provider.divisor'] ??= new \Sylius\MolliePlugin\Provider\DivisorProvider()));
    }
}
