<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_PaymentMethod_Create_Content_Form_Sections_GatewayConfiguration_MollieSubscription_Credentials_Hookable_TestApiKeysActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.payment_method.create.content.form.sections.gateway_configuration.mollie_subscription.credentials.hookable.test_api_keys_action' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.payment_method.create.content.form.sections.gateway_configuration.mollie_subscription.credentials.hookable.test_api_keys_action'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.payment_method.create.content.form.sections.gateway_configuration.mollie_subscription.credentials', 'test_api_keys_action', '@SyliusMolliePlugin/admin/payment_method/form/sections/gateway_configuration/credentials/test_api_keys_action.html.twig', [], [], 0, true);
    }
}
