<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Repository_TemplateMollieEmailTranslationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.repository.template_mollie_email_translation' shared service.
     *
     * @return \Sylius\MolliePlugin\Repository\TemplateMollieEmailTranslationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Repository/TemplateMollieEmailTranslationRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Repository/TemplateMollieEmailTranslationRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius_mollie.repository.template_mollie_email_translation'])) {
            return $container->services['sylius_mollie.repository.template_mollie_email_translation'];
        }

        return $container->services['sylius_mollie.repository.template_mollie_email_translation'] = new \Sylius\MolliePlugin\Repository\TemplateMollieEmailTranslationRepository($a, $a->getClassMetadata('Sylius\\MolliePlugin\\Entity\\TemplateMollieEmailTranslation'));
    }
}
