<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Product_Index_Content_Body_Main_Filters_Controls_Sorting_Menu_Hookable_OldestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.product.index.content.body.main.filters.controls.sorting.menu.hookable.oldest' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.product.index.content.body.main.filters.controls.sorting.menu.hookable.oldest'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_shop.product.index.content.body.main.filters.controls.sorting.menu', 'oldest', '@SyliusShop/product/index/content/body/main/filters/controls/sorting/menu/item.html.twig', [], ['title' => 'sylius.ui.oldest_first', 'sorting' => ['createdAt' => 'asc']], 200, true);
    }
}
