<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Shared_Form_SelectPayment_Payment_Choice_Mollie_Details_PaymentMethods_PaymentMethod_CreditCard_Hookable_FieldsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.shared.form.select_payment.payment.choice.mollie.details.payment_methods.payment_method.credit_card.hookable.fields' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.shared.form.select_payment.payment.choice.mollie.details.payment_methods.payment_method.credit_card.hookable.fields'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_shop.shared.form.select_payment.payment.choice.mollie.details.payment_methods.payment_method.credit_card', 'fields', '@SyliusMolliePlugin/shop/shared/form/select_payment/payment/choice/details/payment_methods/payment_method/credit_card/fields.html.twig', [], [], 0, true);
    }
}
