<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Controller_Shop_PayumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.controller.shop.payum' shared service.
     *
     * @return \Sylius\MolliePlugin\Controller\Shop\PayumController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Controller/Shop/PayumController.php';

        return $container->services['sylius_mollie.controller.shop.payum'] = new \Sylius\MolliePlugin\Controller\Shop\PayumController(($container->services['payum'] ?? $container->load('getPayumService')), ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
