<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Synchronizer_MolliePaymentMethodsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.synchronizer.mollie_payment_methods' shared service.
     *
     * @return \Sylius\MolliePlugin\Updater\MolliePaymentMethodsSynchronizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Updater/MolliePaymentMethodsSynchronizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Updater/MolliePaymentMethodsSynchronizer.php';

        return $container->services['sylius_mollie.synchronizer.mollie_payment_methods'] = new \Sylius\MolliePlugin\Updater\MolliePaymentMethodsSynchronizer(($container->services['sylius.repository.payment_method'] ?? self::getSylius_Repository_PaymentMethodService($container)), ($container->services['sylius.context.channel'] ?? self::getSylius_Context_ChannelService($container)), ($container->services['sylius_mollie.updater.mollie_methods'] ?? $container->load('getSyliusMollie_Updater_MollieMethodsService')));
    }
}
