<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Cart_Index_Content_Hookable_SuggestedProductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.cart.index.content.hookable.suggested_products' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.cart.index.content.hookable.suggested_products'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_shop.cart.index.content', 'suggested_products', 'sylius_shop:product:list', ['limit' => 4, 'template' => '@SyliusShop/product/common/list.html.twig'], [], ['title' => 'sylius.ui.you_may_also_like'], 0, true);
    }
}
