<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusPaypal_Controller_AddToCartService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_paypal.controller.add_to_cart' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\AddToCartAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/AddToCartAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/src/Metadata/MetadataInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Factory/AddToCartCommandFactory.php';

        return $container->services['sylius_paypal.controller.add_to_cart'] = new \Sylius\PayPalPlugin\Controller\AddToCartAction(($container->privates['sylius.factory.add_to_cart_command'] ??= new \Sylius\Bundle\OrderBundle\Factory\AddToCartCommandFactory()), ($container->privates['sylius.context.cart.new_shop_based'] ?? self::getSylius_Context_Cart_NewShopBasedService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sylius.factory.order_item'] ?? $container->load('getSylius_Factory_OrderItemService')), ($container->services['form.factory'] ?? self::getForm_FactoryService($container)), ($container->privates['sylius.resource_registry'] ?? self::getSylius_ResourceRegistryService($container))->get('sylius.order_item'), ($container->privates['sylius_paypal.factory.paypal_payment_method_new_resource'] ?? $container->load('getSyliusPaypal_Factory_PaypalPaymentMethodNewResourceService')), ($container->privates['sylius.modifier.cart.limiting_order_item_quantity'] ?? $container->load('getSylius_Modifier_Cart_LimitingOrderItemQuantityService')), ($container->privates['sylius.modifier.order'] ?? $container->load('getSylius_Modifier_OrderService')), ($container->privates['sylius.resource_controller.request_configuration_factory'] ?? $container->load('getSylius_ResourceController_RequestConfigurationFactoryService')), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
