<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Setter_Order_ItemNamesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.setter.order.item_names' shared service.
     *
     * @return \Sylius\Component\Core\Order\OrderItemNamesSetter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Order/OrderItemNamesSetterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Order/OrderItemNamesSetter.php';

        return $container->services['sylius.setter.order.item_names'] = new \Sylius\Component\Core\Order\OrderItemNamesSetter();
    }
}
