<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Subscription_Processor_SubscriptionScheduleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.subscription.processor.subscription_schedule' shared service.
     *
     * @return \Sylius\MolliePlugin\Subscription\Processor\SubscriptionScheduleProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Subscription/Processor/SubscriptionScheduleProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Subscription/Processor/SubscriptionScheduleProcessor.php';

        return $container->services['sylius_mollie.subscription.processor.subscription_schedule'] = new \Sylius\MolliePlugin\Subscription\Processor\SubscriptionScheduleProcessor(($container->services['sylius_mollie.repository.mollie_subscription_schedule'] ?? $container->load('getSyliusMollie_Repository_MollieSubscriptionScheduleService')), ($container->services['sylius_mollie.subscription.generator.subscription_schedule'] ?? $container->load('getSyliusMollie_Subscription_Generator_SubscriptionScheduleService')));
    }
}
