<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Console_Command_ChangeAdminUserPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.console.command.change_admin_user_password' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Console\Command\ChangeAdminUserPasswordCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Console/Command/ChangeAdminUserPasswordCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Console/Command/Factory/QuestionFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Console/Command/Factory/QuestionFactory.php';

        $container->services['sylius_admin.console.command.change_admin_user_password'] = $instance = new \Sylius\Bundle\AdminBundle\Console\Command\ChangeAdminUserPasswordCommand(($container->services['sylius.repository.admin_user'] ?? $container->load('getSylius_Repository_AdminUserService')), ($container->privates['sylius.security.password_updater'] ?? $container->load('getSylius_Security_PasswordUpdaterService')), ($container->privates['sylius_admin.console.command_factory.question'] ??= new \Sylius\Bundle\AdminBundle\Console\Command\Factory\QuestionFactory()));

        $instance->setName('sylius:admin-user:change-password');
        $instance->setDescription('Change password of admin user');

        return $instance;
    }
}
