<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_EventBus_Middleware_HandleMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.event_bus.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $container->privates['sylius.event_bus.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Symfony\\Component\\Process\\Messenger\\RunProcessMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.MJsV2nf'] ?? $container->load('get_Messenger_HandlerDescriptor_MJsV2nfService'));
        }, 1), 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.x20UZCn'] ?? $container->load('get_Messenger_HandlerDescriptor_X20UZCnService'));
        }, 1), 'Symfony\\Component\\HttpClient\\Messenger\\PingWebhookMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.HXulLHG'] ?? $container->load('get_Messenger_HandlerDescriptor_HXulLHGService'));
        }, 1), 'Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.Bx0I3LS'] ?? $container->load('get_Messenger_HandlerDescriptor_Bx0I3LSService'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.pvbtOpm'] ?? $container->load('get_Messenger_HandlerDescriptor_PvbtOpmService'));
        }, 1), 'Sylius\\Component\\Promotion\\Event\\CatalogPromotionCreated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.6kqGbIT'] ?? $container->load('get_Messenger_HandlerDescriptor_6kqGbITService'));
            yield 1 => ($container->privates['.messenger.handler_descriptor.JFZV9FZ'] ?? $container->load('get_Messenger_HandlerDescriptor_JFZV9FZService'));
        }, 2), 'Sylius\\Component\\Promotion\\Event\\CatalogPromotionUpdated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.p40Cg7g'] ?? $container->load('get_Messenger_HandlerDescriptor_P40Cg7gService'));
            yield 1 => ($container->privates['.messenger.handler_descriptor.OUSxs6T'] ?? $container->load('get_Messenger_HandlerDescriptor_OUSxs6TService'));
        }, 2), 'Sylius\\Component\\Promotion\\Event\\CatalogPromotionEnded' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.cCM7iwY'] ?? $container->load('get_Messenger_HandlerDescriptor_CCM7iwYService'));
            yield 1 => ($container->privates['.messenger.handler_descriptor.juMsYz5'] ?? $container->load('get_Messenger_HandlerDescriptor_JuMsYz5Service'));
        }, 2), 'Sylius\\Component\\Core\\Event\\ProductCreated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.V6_f_7h'] ?? $container->load('get_Messenger_HandlerDescriptor_V6F7hService'));
        }, 1), 'Sylius\\Component\\Core\\Event\\ProductUpdated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.vUzhZII'] ?? $container->load('get_Messenger_HandlerDescriptor_VUzhZIIService'));
        }, 1), 'Sylius\\Component\\Core\\Event\\ProductVariantCreated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.VyW9aZZ'] ?? $container->load('get_Messenger_HandlerDescriptor_VyW9aZZService'));
        }, 1), 'Sylius\\Component\\Core\\Event\\ProductVariantUpdated' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.NUR2fVY'] ?? $container->load('get_Messenger_HandlerDescriptor_NUR2fVYService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Event\\OrderCompleted' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.lmx4unp'] ?? $container->load('get_Messenger_HandlerDescriptor_Lmx4unpService'));
        }, 1)]), true);

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
