<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_PromotionActionCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.form.type.promotion_action_collection' shared service.
     *
     * @return \Sylius\Bundle\PromotionBundle\Form\Type\PromotionActionCollectionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Form/Type/Core/AbstractConfigurationCollectionType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionActionCollectionType.php';

        return $container->privates['sylius.form.type.promotion_action_collection'] = new \Sylius\Bundle\PromotionBundle\Form\Type\PromotionActionCollectionType(($container->privates['sylius.registry.promotion_action'] ?? $container->load('getSylius_Registry_PromotionActionService')));
    }
}
