<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Announcer_CatalogPromotion_RemovalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.announcer.catalog_promotion.removal' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\CatalogPromotion\Announcer\CatalogPromotionRemovalAnnouncer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/Announcer/CatalogPromotionRemovalAnnouncerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/Announcer/CatalogPromotionRemovalAnnouncer.php';

        return $container->services['sylius.announcer.catalog_promotion.removal'] = new \Sylius\Bundle\CoreBundle\CatalogPromotion\Announcer\CatalogPromotionRemovalAnnouncer(($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container)));
    }
}
