<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusShop_Twig_Component_ProductReview_ListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_shop.twig.component.product_review.list' service.
     *
     * @return \Sylius\Bundle\ShopBundle\Twig\Component\ProductReview\ListComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Twig/Component/HookableComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Twig/Component/ProductReview/ListComponent.php';

        $container->factories['service_container']['sylius_shop.twig.component.product_review.list'] = function ($container) {
            return new \Sylius\Bundle\ShopBundle\Twig\Component\ProductReview\ListComponent(($container->services['sylius.repository.product_review'] ?? $container->load('getSylius_Repository_ProductReviewService')));
        };

        return $container->factories['service_container']['sylius_shop.twig.component.product_review.list']($container);
    }
}
