<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Dashboard_Index_Content_Header_TitleBlock_Hookable_ActionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.dashboard.index.content.header.title_block.hookable.actions' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.dashboard.index.content.header.title_block.hookable.actions'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_admin.dashboard.index.content.header.title_block', 'actions', 'sylius_admin:dashboard:channel_selector', ['channelCode' => '@=_context.channel_code', 'template' => '@SyliusAdmin/dashboard/index/component/channel_selector.html.twig'], [], [], 0, true);
    }
}
