<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_HelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.helper' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security.php';

        return $container->privates['security.helper'] = new \Symfony\Bundle\SecurityBundle\Security(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.user_authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.authenticator.managers_locator' => ['privates', 'security.authenticator.managers_locator', 'getSecurity_Authenticator_ManagersLocatorService', true],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'security.firewall.map' => ['privates', 'security.firewall.map', 'getSecurity_Firewall_MapService', false],
            'security.user_checker_locator' => ['privates', 'security.user_checker_locator', 'getSecurity_UserCheckerLocatorService', true],
            'security.firewall.event_dispatcher_locator' => ['privates', 'security.firewall.event_dispatcher_locator', 'getSecurity_Firewall_EventDispatcherLocatorService', true],
            'security.csrf.token_manager' => ['services', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', false],
        ], [
            'security.token_storage' => '?',
            'security.authorization_checker' => '?',
            'security.user_authorization_checker' => '?',
            'security.authenticator.managers_locator' => '?',
            'request_stack' => '?',
            'security.firewall.map' => '?',
            'security.user_checker_locator' => '?',
            'security.firewall.event_dispatcher_locator' => '?',
            'security.csrf.token_manager' => '?',
        ]), ['admin' => new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security.authenticator.form_login.admin' => ['privates', 'security.authenticator.form_login.admin', 'getSecurity_Authenticator_FormLogin_AdminService', true],
            'security.authenticator.remember_me.admin' => ['privates', 'security.authenticator.remember_me.admin', 'getSecurity_Authenticator_RememberMe_AdminService', true],
        ], [
            'security.authenticator.form_login.admin' => '?',
            'security.authenticator.remember_me.admin' => '?',
        ]), 'api_admin' => new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security.authenticator.jwt.api_admin' => ['privates', 'security.authenticator.jwt.api_admin', 'getSecurity_Authenticator_Jwt_ApiAdminService', true],
            'security.authenticator.json_login.api_admin' => ['privates', 'security.authenticator.json_login.api_admin', 'getSecurity_Authenticator_JsonLogin_ApiAdminService', true],
        ], [
            'security.authenticator.jwt.api_admin' => '?',
            'security.authenticator.json_login.api_admin' => '?',
        ]), 'api_shop' => new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security.authenticator.jwt.api_shop' => ['privates', 'security.authenticator.jwt.api_shop', 'getSecurity_Authenticator_Jwt_ApiShopService', true],
            'security.authenticator.json_login.api_shop' => ['privates', 'security.authenticator.json_login.api_shop', 'getSecurity_Authenticator_JsonLogin_ApiShopService', true],
        ], [
            'security.authenticator.jwt.api_shop' => '?',
            'security.authenticator.json_login.api_shop' => '?',
        ]), 'shop' => new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'security.authenticator.form_login.shop' => ['privates', 'security.authenticator.form_login.shop', 'getSecurity_Authenticator_FormLogin_ShopService', true],
            'security.authenticator.json_login.shop' => ['privates', 'security.authenticator.json_login.shop', 'getSecurity_Authenticator_JsonLogin_ShopService', true],
            'security.authenticator.remember_me.shop' => ['privates', 'security.authenticator.remember_me.shop', 'getSecurity_Authenticator_RememberMe_ShopService', true],
        ], [
            'security.authenticator.form_login.shop' => '?',
            'security.authenticator.json_login.shop' => '?',
            'security.authenticator.remember_me.shop' => '?',
        ]), 'image_resolver' => NULL, 'dev' => NULL]);
    }
}
