<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Form_Type_ChannelPriceHistoryConfigService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_admin.form.type.channel_price_history_config' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Form\Type\ChannelPriceHistoryConfigType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Form/Type/ChannelPriceHistoryConfigType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Core/DataMapper/DataMapper.php';

        return $container->privates['sylius_admin.form.type.channel_price_history_config'] = new \Sylius\Bundle\AdminBundle\Form\Type\ChannelPriceHistoryConfigType(($container->services['sylius.repository.taxon'] ?? $container->load('getSylius_Repository_TaxonService')), new \Symfony\Component\Form\Extension\Core\DataMapper\DataMapper());
    }
}
