<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_CatalogPromotion_ProductCreatedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.catalog_promotion.product_created' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\CatalogPromotion\Listener\ProductCreatedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/CatalogPromotion/Listener/ProductCreatedListener.php';

        $a = ($container->privates['sylius.processor.catalog_promotion.product'] ?? $container->load('getSylius_Processor_CatalogPromotion_ProductService'));

        if (isset($container->services['sylius.listener.catalog_promotion.product_created'])) {
            return $container->services['sylius.listener.catalog_promotion.product_created'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sylius.listener.catalog_promotion.product_created'])) {
            return $container->services['sylius.listener.catalog_promotion.product_created'];
        }

        return $container->services['sylius.listener.catalog_promotion.product_created'] = new \Sylius\Bundle\CoreBundle\CatalogPromotion\Listener\ProductCreatedListener(($container->services['sylius.repository.product'] ?? $container->load('getSylius_Repository_ProductService')), $a, $b);
    }
}
