<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Doctrine_Orm_QueryExtension_Shop_Taxon_EnabledChildrenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.doctrine.orm.query_extension.shop.taxon.enabled_children' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Doctrine\ORM\QueryExtension\Shop\Taxon\EnabledChildrenExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Extension/QueryItemExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Doctrine/ORM/QueryExtension/Shop/Taxon/EnabledChildrenExtension.php';

        return $container->privates['sylius_api.doctrine.orm.query_extension.shop.taxon.enabled_children'] = new \Sylius\Bundle\ApiBundle\Doctrine\ORM\QueryExtension\Shop\Taxon\EnabledChildrenExtension(($container->privates['sylius.section_resolver.uri_based'] ?? self::getSylius_SectionResolver_UriBasedService($container)));
    }
}
