<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_MigrationSkipService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.listener.migration_skip' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\MigrationSkipListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/MigrationSkipListener.php';

        $a = ($container->privates['doctrine.migrations.dependency_factory'] ?? $container->load('getDoctrine_Migrations_DependencyFactoryService'));

        if (isset($container->services['sylius.listener.migration_skip'])) {
            return $container->services['sylius.listener.migration_skip'];
        }

        return $container->services['sylius.listener.migration_skip'] = new \Sylius\Bundle\CoreBundle\EventListener\MigrationSkipListener($a);
    }
}
