<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Creator_MollieMethodsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.creator.mollie_methods' shared service.
     *
     * @return \Sylius\MolliePlugin\Creator\MollieMethodsCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Creator/MollieMethodsCreatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Creator/MollieMethodsCreator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Factory/MethodsFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Factory/MethodsFactory.php';

        return $container->services['sylius_mollie.creator.mollie_methods'] = new \Sylius\MolliePlugin\Creator\MollieMethodsCreator(($container->services['sylius_mollie.factory.methods'] ??= new \Sylius\MolliePlugin\Factory\MethodsFactory()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sylius_mollie.custom_factory.mollie_gateway_config'] ?? $container->load('getSyliusMollie_CustomFactory_MollieGatewayConfigService')));
    }
}
