<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_PromotionCoupon_Generate_Content_Form_Sections_General_Hookable_SuffixService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.promotion_coupon.generate.content.form.sections.general.hookable.suffix' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.promotion_coupon.generate.content.form.sections.general.hookable.suffix'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.promotion_coupon.generate.content.form.sections.general', 'suffix', '@SyliusAdmin/promotion_coupon/generate/form/sections/general/suffix.html.twig', [], [], 0, true);
    }
}
