<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_EntityObserver_PriceHistory_ProcessLowestPricesOnChannelChangeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.entity_observer.price_history.process_lowest_prices_on_channel_change' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\PriceHistory\EntityObserver\ProcessLowestPricesOnChannelChangeObserver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/PriceHistory/EntityObserver/EntityObserverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/PriceHistory/EntityObserver/ProcessLowestPricesOnChannelChangeObserver.php';

        return $container->privates['sylius.entity_observer.price_history.process_lowest_prices_on_channel_change'] = new \Sylius\Bundle\CoreBundle\PriceHistory\EntityObserver\ProcessLowestPricesOnChannelChangeObserver(($container->privates['sylius.command_dispatcher.price_history.batched_apply_lowest_price_on_channel_pricings'] ?? $container->load('getSylius_CommandDispatcher_PriceHistory_BatchedApplyLowestPriceOnChannelPricingsService')));
    }
}
