<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Promotion_Create_Content_Form_Sections_Configurationright_Hookable_AppliesToDiscountedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.promotion.create.content.form.sections.configuration#right.hookable.applies_to_discounted' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.promotion.create.content.form.sections.configuration#right.hookable.applies_to_discounted'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.promotion.create.content.form.sections.configuration#right', 'applies_to_discounted', '@SyliusAdmin/promotion/form/sections/configuration/applies_to_discounted.html.twig', [], [], 0, true);
    }
}
