<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusMollie_Admin_PaymentLink_Create_Content_Header_TitleBlock_Actions_Hookable_CreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_mollie.admin.payment_link.create.content.header.title_block.actions.hookable.create' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\DisabledHookable
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/DisabledHookable.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_mollie.admin.payment_link.create.content.header.title_block.actions.hookable.create'] = new \Sylius\TwigHooks\Hookable\DisabledHookable('sylius_mollie.admin.payment_link.create.content.header.title_block.actions', 'create', [], [], NULL);
    }
}
