<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_Listener_AdminAuthenticationSuccessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_api.listener.admin_authentication_success' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\EventListener\AdminAuthenticationSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/EventListener/AdminAuthenticationSuccessListener.php';

        $a = ($container->privates['sylius_api.api_platform.routing.iri_converter'] ?? self::getSyliusApi_ApiPlatform_Routing_IriConverterService($container));

        if (isset($container->privates['sylius_api.listener.admin_authentication_success'])) {
            return $container->privates['sylius_api.listener.admin_authentication_success'];
        }

        return $container->privates['sylius_api.listener.admin_authentication_success'] = new \Sylius\Bundle\ApiBundle\EventListener\AdminAuthenticationSuccessListener($a);
    }
}
