<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Payum_Action_Subscription_CancelRecurringSubscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.payum.action.subscription.cancel_recurring_subscription' shared service.
     *
     * @return \Sylius\MolliePlugin\Payum\Action\Subscription\CancelRecurringSubscriptionAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Action/ActionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/ApiAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Payum/Action/BaseApiAwareAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/GatewayAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/GatewayAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Payum/Action/Subscription/CancelRecurringSubscriptionAction.php';

        return $container->services['sylius_mollie.payum.action.subscription.cancel_recurring_subscription'] = new \Sylius\MolliePlugin\Payum\Action\Subscription\CancelRecurringSubscriptionAction(($container->services['sylius_mollie.logger.mollie_logger_action'] ?? $container->load('getSyliusMollie_Logger_MollieLoggerActionService')));
    }
}
