<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusPaypal_Controller_CompletePaypalOrderFromPaymentPageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_paypal.controller.complete_paypal_order_from_payment_page' shared service.
     *
     * @return \Sylius\PayPalPlugin\Controller\CompletePayPalOrderFromPaymentPageAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Controller/CompletePayPalOrderFromPaymentPageAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Verifier/PaymentAmountVerifierInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/paypal-plugin/src/Verifier/PaymentAmountVerifier.php';

        return $container->services['sylius_paypal.controller.complete_paypal_order_from_payment_page'] = new \Sylius\PayPalPlugin\Controller\CompletePayPalOrderFromPaymentPageAction(($container->privates['sylius_paypal.manager.payment_state'] ?? $container->load('getSyliusPaypal_Manager_PaymentStateService')), ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['sylius_paypal.provider.order'] ?? $container->load('getSyliusPaypal_Provider_OrderService')), ($container->services['sylius_abstraction.state_machine'] ?? self::getSyliusAbstraction_StateMachineService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sylius_paypal.verifier.payment_amount'] ??= new \Sylius\PayPalPlugin\Verifier\PaymentAmountVerifier()), ($container->services['sylius.order_processing.order_processor'] ?? $container->load('getSylius_OrderProcessing_OrderProcessorService')));
    }
}
