<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Provider_StatisticsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.provider.statistics' shared service.
     *
     * @return \Sylius\Component\Core\Statistics\Provider\StatisticsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/StatisticsProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/StatisticsProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/SalesStatisticsProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/SalesStatisticsProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/BusinessActivitySummaryProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Statistics/Provider/BusinessActivitySummaryProvider.php';

        return $container->privates['sylius.provider.statistics'] = new \Sylius\Component\Core\Statistics\Provider\StatisticsProvider(new \Sylius\Component\Core\Statistics\Provider\SalesStatisticsProvider(($container->privates['sylius.registry.statistics.orders_totals_providers'] ?? $container->load('getSylius_Registry_Statistics_OrdersTotalsProvidersService')), $container->parameters['sylius_core.orders_statistics.intervals_map'], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sylius.registry.statistics.orders_totals_providers'] ?? $container->load('getSylius_Registry_Statistics_OrdersTotalsProvidersService'));
            yield 1 => ($container->privates['sylius.registry.statistics.orders_count_provider'] ?? $container->load('getSylius_Registry_Statistics_OrdersCountProviderService'));
        }, 2), ($container->services['cache.app'] ?? self::getCache_AppService($container)), 1800), new \Sylius\Component\Core\Statistics\Provider\BusinessActivitySummaryProvider(($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)), ($container->services['sylius.repository.customer'] ?? $container->load('getSylius_Repository_CustomerService'))));
    }
}
