<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Console_Command_CheckRequirementsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.console.command.check_requirements' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Console\Command\CheckRequirementsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Console/Command/CheckRequirementsCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Checker/RequirementsCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Checker/SyliusRequirementsChecker.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Requirement/SyliusRequirements.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Requirement/RequirementCollection.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Requirement/SettingsRequirements.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Requirement/ExtensionsRequirements.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Requirement/FilesystemRequirements.php';

        $a = ($container->services['translator'] ?? self::getTranslatorService($container));

        $container->services['sylius.console.command.check_requirements'] = $instance = new \Sylius\Bundle\CoreBundle\Console\Command\CheckRequirementsCommand(new \Sylius\Bundle\CoreBundle\Installer\Checker\SyliusRequirementsChecker(new \Sylius\Bundle\CoreBundle\Installer\Requirement\SyliusRequirements([new \Sylius\Bundle\CoreBundle\Installer\Requirement\SettingsRequirements($a), new \Sylius\Bundle\CoreBundle\Installer\Requirement\ExtensionsRequirements($a), new \Sylius\Bundle\CoreBundle\Installer\Requirement\FilesystemRequirements($a, $container->targetDir.'', (\dirname(__DIR__, 3).'/log'))])));

        $instance->setName('sylius:install:check-requirements');
        $instance->setDescription('Checks if all Sylius requirements are satisfied.');

        return $instance;
    }
}
