<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_EventHandler_OrderCompletedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_api.event_handler.order_completed' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\EventHandler\OrderCompletedHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/EventHandler/OrderCompletedHandler.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->services['sylius_api.event_handler.order_completed'])) {
            return $container->services['sylius_api.event_handler.order_completed'];
        }

        return $container->services['sylius_api.event_handler.order_completed'] = new \Sylius\Bundle\ApiBundle\EventHandler\OrderCompletedHandler($a, ($container->services['sylius.repository.order'] ?? self::getSylius_Repository_OrderService($container)));
    }
}
