<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Twig_Component_Dashboard_PendingAction_CountProductReviewsToApproveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.twig.component.dashboard.pending_action.count_product_reviews_to_approve' service.
     *
     * @return \Sylius\Bundle\AdminBundle\Twig\Component\Dashboard\PendingActionCountComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/LiveComponent/HookableLiveComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/TemplatePropTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/Component/Dashboard/PendingActionCountComponent.php';

        $container->factories['sylius_admin.twig.component.dashboard.pending_action.count_product_reviews_to_approve'] = function ($container) {
            return new \Sylius\Bundle\AdminBundle\Twig\Component\Dashboard\PendingActionCountComponent(($container->services['sylius.repository.channel'] ?? self::getSylius_Repository_ChannelService($container)), ($container->privates['sylius_admin.provider.pending_action.count_product_reviews_to_approve'] ?? $container->load('getSyliusAdmin_Provider_PendingAction_CountProductReviewsToApproveService')));
        };

        return $container->factories['sylius_admin.twig.component.dashboard.pending_action.count_product_reviews_to_approve']($container);
    }
}
