<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Validator_OrderShippingMethodEligibilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.validator.order_shipping_method_eligibility' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Validator\Constraints\OrderShippingMethodEligibilityValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Validator/Constraints/OrderShippingMethodEligibilityValidator.php';

        return $container->privates['sylius.validator.order_shipping_method_eligibility'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\OrderShippingMethodEligibilityValidator(($container->privates['sylius.checker.shipping_method_eligibility'] ?? self::getSylius_Checker_ShippingMethodEligibilityService($container)));
    }
}
