<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Twig_Component_Product_FormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.twig.component.product.form' service.
     *
     * @return \Sylius\Bundle\AdminBundle\Twig\Component\Product\FormComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentToolsTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/ComponentWithFormTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/LiveCollectionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/TemplatePropTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/LiveComponent/HookableLiveComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/Component/ResourceFormComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/Component/Product/FormComponent.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Generator/SlugGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Generator/SlugGenerator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/LiveResponder.php';

        $container->factories['sylius_admin.twig.component.product.form'] = function ($container) {
            $a = ($container->services['form.factory'] ?? self::getForm_FactoryService($container));

            if (isset($container->services['sylius_admin.twig.component.product.form'])) {
                return $container->services['sylius_admin.twig.component.product.form'];
            }

            $instance = new \Sylius\Bundle\AdminBundle\Twig\Component\Product\FormComponent(($container->services['sylius.repository.product'] ?? $container->load('getSylius_Repository_ProductService')), $a, 'App\\Entity\\Product\\Product', 'Sylius\\Bundle\\AdminBundle\\Form\\Type\\ProductType', ($container->services['sylius.generator.slug'] ??= new \Sylius\Component\Product\Generator\SlugGenerator()), ($container->services['sylius.repository.product_attribute'] ?? $container->load('getSylius_Repository_ProductAttributeService')), ($container->services['Sylius\\Component\\Product\\Factory\\ProductFactoryInterface'] ?? $container->load('getProductFactoryInterfaceService')));

            $instance->setLiveResponder(($container->privates['ux.live_component.live_responder'] ??= new \Symfony\UX\LiveComponent\LiveResponder()));

            return $instance;
        };

        return $container->factories['sylius_admin.twig.component.product.form']($container);
    }
}
