<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Common_Component_Navbar_Items_Hookable_NotificationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.common.component.navbar.items.hookable.notifications' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.common.component.navbar.items.hookable.notifications'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_admin.common.component.navbar.items', 'notifications', 'sylius_admin:navbar:notifications', ['template' => '@SyliusAdmin/shared/components/navbar/notifications.html.twig'], [], [], 100, true);
    }
}
