<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusMollie_Refund_Guard_OrderPaymentRefundService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_mollie.refund.guard.order_payment_refund' shared service.
     *
     * @return \Sylius\MolliePlugin\Refund\Guard\OrderPaymentRefundGuard
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Refund/Guard/OrderPaymentRefundGuardInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/mollie-plugin/src/Refund/Guard/OrderPaymentRefundGuard.php';

        return $container->services['sylius_mollie.refund.guard.order_payment_refund'] = new \Sylius\MolliePlugin\Refund\Guard\OrderPaymentRefundGuard();
    }
}
