<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Account_AddressBook_Index_Content_Main_Header_Buttons_Hookable_AddAddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.account.address_book.index.content.main.header.buttons.hookable.add_address' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.account.address_book.index.content.main.header.buttons.hookable.add_address'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_shop.account.address_book.index.content.main.header.buttons', 'add_address', '@SyliusShop/account/address_book/index/content/main/header/buttons/add_address.html.twig', [], [], 0, true);
    }
}
