<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusShop_Account_Order_Show_Content_Main_Header_Hookable_MollieCancelSubscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_shop.account.order.show.content.main.header.hookable.mollie_cancel_subscription' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_shop.account.order.show.content.main.header.hookable.mollie_cancel_subscription'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_shop.account.order.show.content.main.header', 'mollie_cancel_subscription', 'sylius_mollie:shop:order:cancel_subscription', ['order' => '@=_context.order', 'template' => '@SyliusMolliePlugin/shop/component/cancel_subscription.html.twig', 'button_config' => ['expanded' => true, 'class' => 'btn btn-warning', 'container_class' => 'd-flex gap-3 justify-content-end mb-3']], [], [], 50, true);
    }
}
