<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Zone_Update_Content_Hookable_FormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.zone.update.content.hookable.form' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.zone.update.content.hookable.form'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_admin.zone.update.content', 'form', 'sylius_admin:zone:form', ['resource' => '@=_context.resource', 'type' => '@=_context.resource.getType()', 'form' => '@=_context.form', 'template' => '@SyliusAdmin/zone/form.html.twig'], [], ['method' => 'PUT'], 0, true);
    }
}
