<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Provider_TaxonTreeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.provider.taxon_tree' shared service.
     *
     * @return \Sylius\Bundle\TaxonomyBundle\Provider\TaxonTreeProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Provider/TaxonTreeProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/TaxonomyBundle/Provider/TaxonTreeProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Tree/RepositoryUtilsInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Tree/RepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Tree/Entity/Repository/AbstractTreeRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Tool/ORM/Repository/EntityRepositoryCompat.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Tree/Entity/Repository/NestedTreeRepository.php';

        $a = ($container->services['sylius.repository.taxon'] ?? $container->load('getSylius_Repository_TaxonService'));

        if (isset($container->privates['sylius.provider.taxon_tree'])) {
            return $container->privates['sylius.provider.taxon_tree'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sylius.provider.taxon_tree'])) {
            return $container->privates['sylius.provider.taxon_tree'];
        }

        return $container->privates['sylius.provider.taxon_tree'] = new \Sylius\Bundle\TaxonomyBundle\Provider\TaxonTreeProvider($a, new \Gedmo\Tree\Entity\Repository\NestedTreeRepository($b, $b->getClassMetadata('App\\Entity\\Taxonomy\\Taxon')));
    }
}
