<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_SearchFilter_Shop_ProductAssociationType_OwnerBasedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_api.search_filter.shop.product_association_type.owner_based' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Doctrine\ORM\Filter\OwnerBasedProductAssociationTypesFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/PropertyAwareFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/ManagerRegistryAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/AbstractFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Doctrine/ORM/Filter/OwnerBasedProductAssociationTypesFilter.php';

        return $container->services['sylius_api.search_filter.shop.product_association_type.owner_based'] = new \Sylius\Bundle\ApiBundle\Doctrine\ORM\Filter\OwnerBasedProductAssociationTypesFilter(($container->privates['sylius.section_resolver.uri_based'] ?? self::getSylius_SectionResolver_UriBasedService($container)), 'App\\Entity\\Product\\ProductAssociation', ($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
