<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_ProductVariant_Create_Content_Form_Sections_MollieRecurring_Body_Hookable_IntervalStepService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.product_variant.create.content.form.sections.mollie_recurring.body.hookable.interval_step' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableTemplate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableTemplate.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.product_variant.create.content.form.sections.mollie_recurring.body.hookable.interval_step'] = new \Sylius\TwigHooks\Hookable\HookableTemplate('sylius_admin.product_variant.create.content.form.sections.mollie_recurring.body', 'interval_step', '@SyliusMolliePlugin/admin/product_variant/form/sections/mollie_recurring/body/interval_step.html.twig', [], [], 0, true);
    }
}
