<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusApi_EventSubscriber_TaxonSlugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_api.event_subscriber.taxon_slug' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\EventSubscriber\TaxonSlugEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/EventSubscriber/TaxonSlugEventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Generator/TaxonSlugGeneratorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php';

        return $container->services['sylius_api.event_subscriber.taxon_slug'] = new \Sylius\Bundle\ApiBundle\EventSubscriber\TaxonSlugEventSubscriber(($container->privates['sylius.generator.taxon_slug'] ??= new \Sylius\Component\Taxonomy\Generator\TaxonSlugGenerator()));
    }
}
