<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusAdmin_Controller_RemoveAvatarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius_admin.controller.remove_avatar' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Action\RemoveAvatarAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Action/RemoveAvatarAction.php';

        return $container->services['sylius_admin.controller.remove_avatar'] = new \Sylius\Bundle\AdminBundle\Action\RemoveAvatarAction(($container->services['sylius.repository.avatar_image'] ?? $container->load('getSylius_Repository_AvatarImageService')), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['security.csrf.token_manager'] ?? self::getSecurity_Csrf_TokenManagerService($container)));
    }
}
