<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusShop_Twig_Component_Product_PriceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_shop.twig.component.product.price' service.
     *
     * @return \Sylius\Bundle\ShopBundle\Twig\Component\Product\PriceComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Twig/Component/HookableComponentTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Twig/Component/Product/PriceComponent.php';

        $container->factories['service_container']['sylius_shop.twig.component.product.price'] = function ($container) {
            return new \Sylius\Bundle\ShopBundle\Twig\Component\Product\PriceComponent(($container->privates['sylius.calculator.product_variant_price'] ?? self::getSylius_Calculator_ProductVariantPriceService($container)), ($container->privates['sylius.formatter.money'] ??= new \Sylius\Bundle\MoneyBundle\Formatter\MoneyFormatter()), ($container->services['sylius.context.channel'] ?? self::getSylius_Context_ChannelService($container)), ($container->services['sylius.context.locale'] ?? self::getSylius_Context_LocaleService($container)), ($container->services['sylius.context.currency'] ?? self::getSylius_Context_CurrencyService($container)), ($container->privates['sylius.converter.currency'] ?? self::getSylius_Converter_CurrencyService($container)));
        };

        return $container->factories['service_container']['sylius_shop.twig.component.product.price']($container);
    }
}
