<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyliusTwigHooks_Hook_SyliusAdmin_Order_History_Content_Sections_Addresses_Hookable_ShippingAddressService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius_twig_hooks.hook.sylius_admin.order.history.content.sections.addresses.hookable.shipping_address' shared service.
     *
     * @return \Sylius\TwigHooks\Hookable\HookableComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/AbstractHookable.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/twig-hooks/src/Hookable/HookableComponent.php';

        return $container->privates['sylius_twig_hooks.hook.sylius_admin.order.history.content.sections.addresses.hookable.shipping_address'] = new \Sylius\TwigHooks\Hookable\HookableComponent('sylius_admin.order.history.content.sections.addresses', 'shipping_address', 'sylius_admin:order:address_history', ['addressId' => '@=_context.resource.getShippingAddress().getId()', 'header' => 'sylius.ui.shipping_address', 'sort' => 'desc', 'template' => '@SyliusAdmin/order/history/content/sections/addresses/shipping_address.html.twig'], [], [], 0, true);
    }
}
