<?php

namespace Container2uyByNp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_EventSubscriber_GenerateProductVariantsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.event_subscriber.generate_product_variants' shared service.
     *
     * @return \Sylius\Bundle\ProductBundle\Form\EventSubscriber\GenerateProductVariantsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/GenerateProductVariantsSubscriber.php';

        return $container->services['sylius.form.event_subscriber.generate_product_variants'] = new \Sylius\Bundle\ProductBundle\Form\EventSubscriber\GenerateProductVariantsSubscriber(($container->services['sylius.generator.product_variant'] ?? $container->load('getSylius_Generator_ProductVariantService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
