<?php

namespace Proxies\__CG__\App\Entity\Channel;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ChannelPriceHistoryConfig extends \App\Entity\Channel\ChannelPriceHistoryConfig implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'lowestPriceForDiscountedProductsCheckingPeriod' => [parent::class, 'lowestPriceForDiscountedProductsCheckingPeriod', null, 8],
        "\0".'*'."\0".'lowestPriceForDiscountedProductsVisible' => [parent::class, 'lowestPriceForDiscountedProductsVisible', null, 8],
        "\0".'*'."\0".'taxonsExcludedFromShowingLowestPrice' => [parent::class, 'taxonsExcludedFromShowingLowestPrice', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'lowestPriceForDiscountedProductsCheckingPeriod' => [parent::class, 'lowestPriceForDiscountedProductsCheckingPeriod', null, 8],
        'lowestPriceForDiscountedProductsVisible' => [parent::class, 'lowestPriceForDiscountedProductsVisible', null, 8],
        'taxonsExcludedFromShowingLowestPrice' => [parent::class, 'taxonsExcludedFromShowingLowestPrice', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
